import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

import {
  AppTheoryMicrovmController,
  AppTheoryMicrovmImage,
  AppTheoryMicrovmNetworkConnector,
} from "@theory-cloud/apptheory-cdk";
import * as cdk from "aws-cdk-lib";
import * as customresources from "aws-cdk-lib/custom-resources";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as iam from "aws-cdk-lib/aws-iam";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as s3assets from "aws-cdk-lib/aws-s3-assets";
import type { Construct } from "constructs";

export const HOSTED_GENESIS_MICROVM_NAMESPACE = "hosted-genesis" as const;
export const HOSTED_GENESIS_MICROVM_SOURCE_OF_TRUTH =
  "host-dynamodb-hosted-genesis-session" as const;
export const HOSTED_GENESIS_MICROVM_MAXIMUM_DURATION_SECONDS = 300 as const;
export const HOSTED_GENESIS_MICROVM_IDLE_MAX_SECONDS = 300 as const;
export const HOSTED_GENESIS_MICROVM_IDLE_SUSPENDED_SECONDS = 1800 as const;
export const HOSTED_GENESIS_MICROVM_IDLE_AUTO_RESUME_ENABLED = false as const;

// P52 H1 step 2 (F1): the AWS-managed base MicroVM image ARN. This is the
// foundation the entire MicroVM-only genesis program sits on — H1.1–H1.5 merged
// without it and the first real deploy failed. The verified ARN is sourced
// directly from AWS Lambda MicroVM developer-guide documentation (see the
// comment at the call site for the exact doc URLs and quoted commands). It is
// pinned as a literal here (NOT operator-supplied context, NOT a formatArn
// placeholder) so a real `cdk deploy` resolves the AWS::Lambda::MicrovmImage
// build against the Lambda-service-owned managed base runtime.
//
// ARN shape: arn:aws:lambda:<region>:aws:microvm-image:<runtime-name>
//   - account position: the literal string `aws` (service-owned resource
//     pattern), NOT a numeric AWS account, NOT the CDK placeholder
//     `123456789012`.
//   - separator before the runtime name is a COLON, not a slash.
//   - runtime name: `al2023-1` (Amazon Linux 2023) — the only managed MicroVM
//     base runtime documented by AWS (others may exist via the
//     list-managed-microvm-images API, but only al2023-1 is documented).
//
// Region: qualified for us-east-1. The stack deploys in a single region; a
// future multi-region deploy would need to parameterize this segment (a
// separate change, out of F1 scope — cdk.Aws.REGION cannot be embedded in a
// literal ARN string).
//
// AppTheory's AppTheoryMicrovmImage construct passes baseImageArn through
// verbatim (no pin, no default, no validation beyond whitespace/length — see
// @theory-cloud/apptheory-cdk microvm-image.ts:365,381), so this literal flows
// straight to the AWS::Lambda::MicrovmImage BaseImageArn property.
export const HOSTED_GENESIS_MICROVM_BASE_IMAGE_ARN =
  "arn:aws:lambda:us-east-1:aws:microvm-image:al2023-1" as const;

// P52 corrective #873: the AppTheory MicroVM path takes NO caller-supplied
// context for deployed stages. Egress uses the AWS-managed internetEgress
// connector (zero synthesized resources); the MicrovmImage build role is
// host-owned; and the authorizer bearer token is CDK-owned — generated by a
// Lambda-backed custom resource during `theory app up` / `cdk deploy` and
// written to a deterministic SSM SecureString. There is no manual
// `aws ssm put-parameter` step, no `hostedGenesisMicrovmAuthorizerTokenSha256`
// context, and no `hostedGenesisMicrovmAuthTokenSSMParamName` context. As of
// H1 step 2 (F1) the base image ARN is also NO LONGER operator-supplied context
// — it is the pinned AWS-managed managed-base literal above
// (HOSTED_GENESIS_MICROVM_BASE_IMAGE_ARN). The only remaining context is the
// dev/test-only opt-out (`hostedGenesisMicrovmDevTestOptOut`).
const contextKeys = {
  devTestOptOut: "hostedGenesisMicrovmDevTestOptOut",
} as const;

// authTokenSSMParamName is the deterministic NAME (not the value) of the SSM
// SecureString that holds the raw authorizer bearer token the control plane
// presents to the controller API. The param name is non-secret and stable per
// stage; the raw token VALUE is a credential the CDK custom resource
// (provisionHostedGenesisMicrovmAuthToken below) generates and writes during
// deploy — never in git, context, logs, CloudFormation output, docs, or
// fixtures. The control plane loads the raw token from this param at runtime.
function authTokenSSMParamName(stage: string): string {
  return `/lesser-host/${stage}/hosted-genesis/microvm/auth-token`;
}

export interface HostedGenesisMicrovmProps {
  readonly stage: string;
  readonly namePrefix: string;
  readonly repoRoot: string;
  readonly removalPolicy: cdk.RemovalPolicy;
  readonly stateTable: dynamodb.ITable;
  // controlPlaneFunction is the control-plane API Lambda that, under P52 H1.5,
  // dispatches MicroVM runs through the governed AppTheoryMicrovmController HTTP
  // API (POST /microvms to run, GET /microvms/{session_id} to reconcile) via an
  // HTTPControllerDispatcher wired in controlplane.NewServer. When provided, the
  // construct grants it ssm:GetParameter on the authorizer bearer-token
  // SecureString and injects the controller endpoint + auth-token SSM param name
  // + image/network-connector refs env vars so NewServer can build the real HTTP
  // dispatcher. The control plane never receives MicroVM IAM or session-registry
  // access — the controller Lambda is the single governed surface. Fail-closed
  // auth is preserved: the controller routes stay authorizer-required +
  // deny-by-default regardless of this grant.
  readonly controlPlaneFunction?: lambda.Function;
  // aiWorkerFunction consumes the HostedGenesisQueue and performs the actual
  // AppTheory MicroVM run/invoke handoff after the accept path has returned
  // 202. It receives the same HTTP dispatcher env + auth-token SSM grant as the
  // control plane, but still receives no raw MicroVM IAM/session-registry
  // access; it only speaks to the governed controller API.
  readonly aiWorkerFunction?: lambda.Function;
}

export interface HostedGenesisMicrovmResult {
  readonly enabled: boolean;
  readonly controller?: AppTheoryMicrovmController;
}

export function configureHostedGenesisMicrovm(
  scope: Construct,
  props: HostedGenesisMicrovmProps,
): HostedGenesisMicrovmResult {
  if (devTestOptOut(scope, props.stage)) {
    return { enabled: false };
  }
  // P52 corrective repair: deployed stages (lab AND live) must dogfood the
  // AppTheory MicroVM construct path. The path now takes NO caller-supplied
  // context for deployed stages — the authorizer bearer token is CDK-owned
  // (generated by the custom resource below). Fail-closed runtime behavior is
  // still preserved: the AppTheoryMicrovmController construct always sets
  // AUTH_REQUIRED=true and AUTH_DEFAULT=deny, the authorizer is attached to
  // every route, and the controller runtime re-checks both env vars at startup
  // (refusing to serve if either is loosened).

  // P52 corrective #873: host CDK owns the authorizer bearer token. The custom
  // resource generates a strong random bearer, writes the RAW token to the
  // deterministic SSM SecureString, and returns ONLY the sha256 digest + the
  // param name to CloudFormation. The raw token never enters CDK context,
  // logs, CloudFormation output, docs, or fixtures — it exists only in the
  // custom-resource Lambda runtime and the SSM SecureString value. The authorizer
  // + controller env digest and the control-plane SSM-param-name grant both flow
  // from this resource's getAtt, so the digest is a CloudFormation token (not a
  // literal) and the param name is deterministic. This removes the prior manual
  // `aws ssm put-parameter` operator step + the two CDK context values that
  // backed it.
  const tokenProvisioning = provisionHostedGenesisMicrovmAuthToken(
    scope,
    "HostedGenesisMicrovmAuthToken",
    {
      stage: props.stage,
      paramName: authTokenSSMParamName(props.stage),
      removalPolicy: props.removalPolicy,
    },
  );
  const authTokenSha256 = tokenProvisioning.authTokenSha256;
  const authTokenSSMParam = tokenProvisioning.paramName;

  // P52 corrective #873: egress uses the AWS-managed INTERNET_EGRESS connector
  // (AppTheoryMicrovmNetworkConnector.internetEgress). It synthesizes NO
  // CloudFormation resources — it is a typed reference to the AWS-managed
  // public-internet egress connector — so host needs no caller VPC, subnet,
  // availability zone, or security group for the MicroVM path. The hosted-genesis
  // workload is a lifecycle-hook server: it receives hook POSTs inbound and calls
  // out only to public-internet endpoints (the assistant LLM provider + the host
  // DynamoDB endpoint); it has no VPC-private dependencies, so AWS-managed
  // internet egress is the correct, sufficient, framework-provided connector.
  // The framework sets networkConnectorKind=EGRESS on this reference, which
  // satisfies both the image's egressNetworkConnectors slot and the controller's
  // EGRESS kind check.
  const egressConnector = AppTheoryMicrovmNetworkConnector.internetEgress(
    scope,
    "HostedGenesisMicrovmEgressConnector",
  );
  // AWS rejects CreateMicrovmAuthToken when ALL_INGRESS is combined with any
  // other ingress connector. Host also wires SHELL_INGRESS for governed shell
  // token support, so the workload endpoint must use HTTP_INGRESS explicitly.
  // AppTheory v1.17.0 exposes the documented AWS-managed HTTP_INGRESS connector
  // directly, preserving the framework's typed INGRESS boundary.
  const ingressConnector = AppTheoryMicrovmNetworkConnector.httpIngress(
    scope,
    "HostedGenesisMicrovmHttpIngressConnector",
  );
  const shellIngressConnector = AppTheoryMicrovmNetworkConnector.shellIngress(
    scope,
    "HostedGenesisMicrovmShellIngressConnector",
  );

  // P52 corrective #873: host owns the AWS::Lambda::MicrovmImage build role.
  // AppTheory's construct validates buildRoleArn but does not create it (the
  // example pins a placeholder role name); AWS requires a role the MicroVM
  // image build service (lambda.amazonaws.com) can assume with permission to
  // fetch the code artifact + build the image. Host creates it here with
  // minimum trust + permissions instead of demanding a hand-supplied ARN,
  // eliminating hostedGenesisMicrovmBuildRoleArn context. The role is granted
  // s3:GetObject on the workload asset bucket + the MicroVM image build/delete
  // actions scoped to this image; no broader account access.
  // (2026-07-04) The trust principal is lambda.amazonaws.com, NOT
  // microvms.lambda.amazonaws.com — AWS rejects the latter with
  // "IAM Invalid principal in policy: SERVICE microvms.lambda.amazonaws.com".
  const workloadArtifact = buildHostedGenesisMicrovmWorkloadAsset(
    scope,
    "HostedGenesisMicrovmWorkloadArtifact",
    props.repoRoot,
  );
  const buildRole = createHostedGenesisMicrovmImageBuildRole(
    scope,
    "HostedGenesisMicrovmImageBuildRole",
    props.namePrefix,
    props.stage,
    workloadArtifact,
  );

  // AWS RunMicrovm assumes this explicit execution role for the guest workload.
  // The workload reloads the platform-supplied credentials and builds a fresh
  // TableTheory store per turn; it must not re-assume this same role. Keep image
  // build authority and runtime authority separate: the build role has no
  // sts:AssumeRole grant and is not trusted by the execution role.
  const executionRole = createHostedGenesisMicrovmExecutionRole(
    scope,
    "HostedGenesisMicrovmExecutionRole",
    props.namePrefix,
    props.stage,
    props.stateTable,
  );

  // P52 H1 step 2 (F1): the base image ARN is the AWS-managed MicroVM base
  // runtime, NOT operator-supplied context and NOT a synthesized placeholder.
  // The verified managed-base ARN is sourced directly from AWS Lambda MicroVM
  // developer-guide documentation (quoted verbatim below); pinning it as a
  // literal here closes F1 — the foundation the entire MicroVM-only genesis
  // program sits on — so a real `cdk deploy` produces an AWS::Lambda::MicrovmImage
  // whose build resolves against the Lambda-service-owned base.
  //
  // Verified ARN (us-east-1; region is per-deployment — AWS_REGION is already
  // baked into the image env, and the stack deploys in a single region):
  //   arn:aws:lambda:us-east-1:aws:microvm-image:al2023-1
  //
  // Authoritative AWS documentation sources (each quotes this exact ARN):
  //   - Lambda developer guide, "Create your first Lambda MicroVM", Step 3:
  //     https://docs.aws.amazon.com/lambda/latest/dg/microvms-getting-started.html
  //       aws lambda-microvms create-microvm-image \
  //         --base-image-arn arn:aws:lambda:{{us-east-1}}:aws:microvm-image:al2023-1
  //   - Lambda developer guide, "MicroVM images" (3 separate code examples —
  //     list-managed-microvm-image-versions, update-microvm-image,
  //     create-microvm-image with --additional-os-capabilities):
  //     https://docs.aws.amazon.com/lambda/latest/dg/microvms-images.html
  //       aws lambda-microvms list-managed-microvm-image-versions \
  //         --image-identifier arn:aws:lambda:{{us-east-1}}:aws:microvm-image:al2023-1
  //
  // Two load-bearing details the prior deploys got wrong:
  //   1. Account: the literal string `aws` (the standard AWS pattern for
  //      service-owned resources — Lambda owns the managed base images), NOT a
  //      numeric AWS account and NOT the CDK placeholder `123456789012`. The
  //      2026-07-04 deploy failed with "No managed runtime with arn
  //      arn:aws:lambda:us-east-1:693925625407:microvm-image/base" precisely
  //      because host's formatArn account-scoped the ARN to the customer account
  //      (693925625407) where no managed base image exists.
  //   2. Separator + runtime name: the managed base uses a COLON before the
  //      runtime name (`microvm-image:al2023-1`), NOT a slash, and the runtime
  //      name is `al2023-1` (Amazon Linux 2023), NOT `base`. The AppTheory
  //      example ARN `arn:aws:lambda:us-east-1:123456789012:microvm-image/base`
  //      is wrong on both counts — it is a non-deploying synth placeholder, not
  //      an AWS-managed runtime, and must not be used.
  //
  // AppTheory's AppTheoryMicrovmImage construct passes baseImageArn through
  // verbatim (no pin, no default, no validation beyond whitespace/length — see
  // @theory-cloud/apptheory-cdk microvm-image.ts:365,381), so this literal flows
  // straight to the AWS::Lambda::MicrovmImage BaseImageArn property. It is
  // region-qualified for us-east-1; a future multi-region deploy would need to
  // parameterize the region segment (cdk.Aws.REGION cannot be embedded in a
  // literal ARN string — that is a separate change, out of F1 scope).
  const baseImageArn = HOSTED_GENESIS_MICROVM_BASE_IMAGE_ARN;
  // baseImageVersion "0" is the only AVAILABLE managed version for al2023-1,
  // verified via `aws lambda-microvms list-managed-microvm-image-versions
  //   --image-identifier arn:aws:lambda:us-east-1:aws:microvm-image:al2023-1`
  // (factory, 2026-07-04). The 2026-07-04 lab deploy failed on
  // HostedGenesisMicrovmImage CREATE_FAILED: "No managed runtime with arn
  // arn:aws:lambda:us-east-1:aws:microvm-image:al2023-1 and version 1 is
  // available." — the ARN is correct; "1" was the wrong version. The API
  // returned only {"imageVersion": "0"} for this image.
  const baseImageVersion = "0";

  // AppTheory v1.17.0 is the formal replacement for Host's temporary
  // MicroVM image L1 bridge. Endpoint-dispatched hosted-genesis images now use
  // the framework construct directly with `hooks: {}`: AppTheory synthesizes an
  // explicit empty Hooks object, Lambda builds the image without AWS-invoked
  // lifecycle hooks, and runtime HTTP traffic is delivered through the MicroVM
  // endpoint on the default port 8080.
  const microvmImage = new AppTheoryMicrovmImage(
    scope,
    "HostedGenesisMicrovmImage",
    {
      name: `${props.namePrefix}_hosted_genesis`,
      description: "AppTheory MicroVM image for hosted-genesis dogfood",
      baseImageArn,
      baseImageVersion,
      buildRoleArn: buildRole.roleArn,
      codeArtifact: { uri: workloadArtifact.s3ObjectUrl },
      egressNetworkConnectors: [egressConnector],
      environmentVariables: [
        {
          key: "HOSTED_GENESIS_MICROVM_NAMESPACE",
          value: HOSTED_GENESIS_MICROVM_NAMESPACE,
        },
        {
          key: "HOSTED_GENESIS_MICROVM_SOURCE_OF_TRUTH",
          value: HOSTED_GENESIS_MICROVM_SOURCE_OF_TRUTH,
        },
        {
          key: "STATE_TABLE_NAME",
          value: props.stateTable.tableName,
        },
      ],
      hooks: {},
      logging: {
        cloudWatch: {
          logGroup: `/aws/lambda/microvms/${props.namePrefix}_hosted_genesis`,
          logStream: "build",
        },
      },
      resources: [{ minimumMemoryInMiB: 2048 }],
      tags: {
        Service: "lesser-host",
        Stage: props.stage,
        Purpose: "hosted-genesis-microvm-dogfood",
      },
    },
  );
  // The temporary Host L1 bridge used the top-level CloudFormation logical ID
  // `HostedGenesisMicrovmImage`. AppTheory's first-class construct owns a child
  // `MicrovmImage` resource, which would otherwise synthesize a new logical ID
  // and force CloudFormation to create a second image with the same Name before
  // deleting the old one. AWS rejects that replacement as AlreadyExists, so
  // preserve the deployed logical ID and let CloudFormation update the existing
  // MicroVM image in place.
  microvmImage.microvmImage.overrideLogicalId("HostedGenesisMicrovmImage");

  const authorizer = new lambda.Function(
    scope,
    "HostedGenesisMicrovmAuthorizer",
    {
      functionName: `${props.namePrefix}-hosted-genesis-microvm-authorizer`,
      description: "Fail-closed AppTheory MicroVM controller authorizer",
      code: buildGoBootstrapAsset(
        props.repoRoot,
        "HostedGenesisMicrovmAuthorizer",
        "./cmd/hosted-genesis-microvm-authorizer",
      ),
      handler: "bootstrap",
      runtime: lambda.Runtime.PROVIDED_AL2023,
      architecture: lambda.Architecture.X86_64,
      memorySize: 128,
      timeout: cdk.Duration.seconds(5),
      environment: {
        STAGE: props.stage,
        APPTHEORY_MICROVM_AUTHORIZER_TOKEN_SHA256: authTokenSha256,
        HOSTED_GENESIS_MICROVM_AUTH_TOKEN_SHA256: authTokenSha256,
      },
    },
  );

  // P52 H1.5 corrective: host owns the MicroVM execution role passed to
  // RunMicrovm via AppTheoryMicrovmController.executionRole. The AppTheory
  // controller reads APPTHEORY_MICROVM_EXECUTION_ROLE_ARN from its env and
  // propagates it through ProviderRunInput.ExecutionRoleArn into
  // lambdamicrovms.RunMicrovmInput.ExecutionRoleArn; the construct grants the
  // controller Lambda iam:PassRole on this role and emits the ARN env var. AWS
  // Lambda MicroVMs assume this role (lambda.amazonaws.com trust) for the
  // in-VM workload, so the workload can reach Host state + SSM provider keys
  // WITHOUT raw credentials in the image env. The control plane still has no
  // MicroVM IAM; it only speaks HTTP to the governed controller API.
  //
  // Least-privilege: DynamoDB read/write on the Host state table only, SSM
  // GetParameter + KMS Decrypt for the existing provider-key SecureString params
  // (the workload's SSM fallback reads /lesser-host/api/openai/service and
  // /lesser-host/api/claude), and X-Ray/CloudWatch emission for the in-VM
  // process. No wildcard DynamoDB, no broader SSM, no PassRole, no IAM. Raw
  // secrets never enter the image env or CloudFormation — only param NAMES.
  const controller = new AppTheoryMicrovmController(
    scope,
    "HostedGenesisMicrovmController",
    {
      apiName: `${props.namePrefix}-hosted-genesis-microvm`,
      controller: {
        functionName: `${props.namePrefix}-hosted-genesis-microvm-controller`,
        runtime: lambda.Runtime.PROVIDED_AL2023,
        handler: "bootstrap",
        code: buildGoBootstrapAsset(
          props.repoRoot,
          "HostedGenesisMicrovmController",
          "./cmd/hosted-genesis-microvm-controller",
        ),
        description:
          "Hosted-genesis AppTheory MicroVM controller using runtime/microvm primitives",
        architecture: lambda.Architecture.X86_64,
        memorySize: 512,
        timeout: cdk.Duration.seconds(30),
        environment: {
          STAGE: props.stage,
          HOSTED_GENESIS_MICROVM_NAMESPACE: HOSTED_GENESIS_MICROVM_NAMESPACE,
          HOSTED_GENESIS_MICROVM_SOURCE_OF_TRUTH:
            HOSTED_GENESIS_MICROVM_SOURCE_OF_TRUTH,
          HOSTED_GENESIS_MICROVM_AUTH_TOKEN_SHA256: authTokenSha256,
          HOSTED_GENESIS_MICROVM_MAXIMUM_DURATION_SECONDS: String(
            HOSTED_GENESIS_MICROVM_MAXIMUM_DURATION_SECONDS,
          ),
          HOSTED_GENESIS_MICROVM_IDLE_MAX_SECONDS: String(
            HOSTED_GENESIS_MICROVM_IDLE_MAX_SECONDS,
          ),
          HOSTED_GENESIS_MICROVM_IDLE_SUSPENDED_SECONDS: String(
            HOSTED_GENESIS_MICROVM_IDLE_SUSPENDED_SECONDS,
          ),
          HOSTED_GENESIS_MICROVM_IDLE_AUTO_RESUME_ENABLED: String(
            HOSTED_GENESIS_MICROVM_IDLE_AUTO_RESUME_ENABLED,
          ),
          STATE_TABLE_NAME: props.stateTable.tableName,
        },
      },
      authorizer,
      authorizerName: `${props.namePrefix}-hosted-genesis-microvm-authorizer`,
      authorizerHeaderName: "Authorization",
      authorizerCacheTtl: cdk.Duration.seconds(0),
      microvmImage,
      ingressNetworkConnectors: [ingressConnector],
      egressNetworkConnectors: [egressConnector],
      shellIngressNetworkConnector: shellIngressConnector,
      // P52 H1.5 corrective: the host-owned execution role
      // the controller propagates to RunMicrovm. The construct emits its ARN as
      // APPTHEORY_MICROVM_EXECUTION_ROLE_ARN on the controller Lambda and grants
      // the controller iam:PassRole on it. See executionRole doc above.
      executionRole,
      sessionTableName: `${props.namePrefix}-hosted-genesis-microvm-sessions`,
      sessionTableRemovalPolicy: props.removalPolicy,
      sessionTableDeletionProtection: false,
      enableSessionTablePointInTimeRecovery: true,
      stage: {
        stageName: props.stage,
        accessLogging: true,
        throttlingRateLimit: 10,
        throttlingBurstLimit: 20,
      },
    },
  );
  props.stateTable.grantReadWriteData(controller.controllerFunction);
  grantHostedGenesisMicrovmControllerRunPermissions(
    controller.controllerFunction,
  );

  // P52 H1.5: provisioned concurrency on the controller Lambda keeps the
  // governed HTTP API warm so the control plane's accept-path dispatch
  // (POST /microvms) meets the <2s budget without a controller cold-start hit.
  // currentVersionOptions alone does not publish a version/alias at synth time
  // (CDK only materializes them when currentVersion is referenced), so publish
  // an explicit alias carrying provisioned concurrency. The controller Lambda
  // itself is created by the AppTheoryMicrovmController construct from the
  // caller-supplied FunctionProps; this alias is the CDK-supported way to add
  // provisioned concurrency to a Function constructed elsewhere.
  const controllerVersion = controller.controllerFunction.currentVersion;
  new lambda.Alias(scope, "HostedGenesisMicrovmControllerAlias", {
    aliasName: "provisioned",
    version: controllerVersion,
    provisionedConcurrentExecutions: 1,
  });

  // P52 H1.5/P53: grant Host dispatch Lambdas ssm:GetParameter on the
  // authorizer bearer-token SecureString + inject the controller endpoint +
  // auth-token SSM param name + image/network-connector refs env vars so they
  // can construct the HTTPControllerDispatcher. The control plane uses this for
  // recovery/extraction; ai-worker uses it for the queued accept-path handoff.
  // Neither Lambda receives raw MicroVM IAM or session-registry access — both
  // only speak HTTP to the governed controller API with the authorizer bearer
  // token (loaded from SSM at runtime, never committed or logged). Fail-closed
  // auth on the controller routes is unaffected.
  for (const dispatchFn of [
    props.controlPlaneFunction,
    props.aiWorkerFunction,
  ].filter((fn): fn is lambda.Function => !!fn)) {
    // AppTheory v1.17 treats controller image/network refs as deployment-pinned
    // defaults and rejects caller-supplied overrides that do not exactly match
    // those pinned refs. Keep the control-plane dispatcher env in lockstep with
    // the controller's ingress set (HTTP endpoint ingress + governed shell
    // ingress) so POST /microvms cannot drift from the controller deployment
    // contract. This is connector metadata only; the control plane still has no
    // MicroVM IAM and cannot issue shell tokens.
    grantFunctionMicroVMDispatch(
      scope,
      dispatchFn,
      controller.endpoint,
      microvmImage.microvmImageArn,
      [
        ingressConnector.networkConnectorArn,
        shellIngressConnector.networkConnectorArn,
      ],
      [egressConnector.networkConnectorArn],
      authTokenSSMParam,
    );
  }

  new cdk.CfnOutput(scope, "HostedGenesisMicrovmControllerEndpoint", {
    value: controller.endpoint,
    description:
      "AppTheory MicroVM controller endpoint (operator canary only, never browser/public Host response).",
  });
  new cdk.CfnOutput(scope, "HostedGenesisMicrovmSessionRegistryTable", {
    value: controller.sessionTable.tableName,
    description:
      "AppTheory MicroVM session registry cache; Host HostedGenesisSession remains business truth.",
  });

  // P52 H1 step 2 (F1): expose the genesis MicroVM image ARN + State so factory
  // can verify a real deploy produced an ACTIVE image. Both are Fn::GetAtt tokens
  // on the AWS::Lambda::MicrovmImage resource (ImageArn + State — see
  // AWSCloudFormation UserGuide aws-resource-lambda-microvmimage.html return
  // values), read directly off the AppTheoryMicrovmImage construct as
  // microvmImageArn / microvmImageState. They resolve
  // only after CloudFormation creates the image and its asynchronous build
  // transitions CREATING -> CREATED (State=ACTIVE), so `cdk deploy` /
  // describe-stacks is the F1 verification surface. This step does NOT deploy;
  // the principal deploys and factory reads these outputs to confirm
  // State=ACTIVE — the F1 deploy proof.
  new cdk.CfnOutput(scope, "HostedGenesisMicrovmImageArn", {
    value: microvmImage.microvmImageArn,
    description:
      "ARN of the hosted-genesis AWS::Lambda::MicrovmImage (Fn::GetAtt ImageArn); resolves post-deploy.",
  });
  new cdk.CfnOutput(scope, "HostedGenesisMicrovmImageState", {
    value: microvmImage.microvmImageState,
    description:
      "State of the hosted-genesis AWS::Lambda::MicrovmImage (Fn::GetAtt State); factory verifies State=ACTIVE after a real deploy.",
  });

  return { enabled: true, controller };
}

function grantHostedGenesisMicrovmControllerRunPermissions(
  fn: lambda.Function,
): void {
  // 2026-07-07 lab evidence: AppTheory grants these Lambda MicroVM
  // control-plane actions on `arn:...:microvm:*`, but IAM policy simulation for
  // the deployed lab controller role evaluates `lambda:RunMicrovm` as
  // implicitDeny for that resource shape. The Lambda MicroVM service currently
  // behaves like permission-only control actions here, so Host adds a narrowly
  // action-scoped wildcard-resource supplement until the framework grant can be
  // corrected upstream. This does NOT widen iam:PassRole (still scoped by the
  // AppTheory construct to the host-owned execution role) and does NOT give the
  // browser/control plane MicroVM IAM; only the fail-closed controller Lambda can
  // use these actions.
  fn.addToRolePolicy(
    new iam.PolicyStatement({
      sid: "HostedGenesisMicrovmControlPlaneWildcard",
      actions: [
        "lambda:CreateMicrovmAuthToken",
        "lambda:CreateMicrovmShellAuthToken",
        "lambda:GetMicrovm",
        "lambda:ResumeMicrovm",
        "lambda:RunMicrovm",
        "lambda:SuspendMicrovm",
        "lambda:TerminateMicrovm",
      ],
      resources: ["*"],
    }),
  );
}

function grantFunctionMicroVMDispatch(
  scope: Construct,
  fn: lambda.Function,
  controllerEndpoint: string,
  imageArn: string,
  ingressConnectorArns: string[],
  egressConnectorArns: string[],
  authTokenSSMParamName: string,
): void {
  const authTokenSSMParamArn = ssmParamArn(scope, authTokenSSMParamName);

  fn.addToRolePolicy(
    new iam.PolicyStatement({
      sid: "HostedGenesisMicrovmAuthTokenRead",
      actions: ["ssm:GetParameter", "ssm:GetParameters"],
      resources: [authTokenSSMParamArn],
    }),
  );

  fn.addToRolePolicy(
    new iam.PolicyStatement({
      sid: "HostedGenesisMicrovmAuthTokenDecrypt",
      actions: ["kms:Decrypt"],
      resources: ["*"],
      conditions: {
        StringEquals: {
          "kms:ViaService": `ssm.${cdk.Aws.REGION}.amazonaws.com`,
        },
      },
    }),
  );

  // Inject the env vars controlplane.NewServer's HTTP dispatcher constructor
  // reads: the governed controller endpoint, the auth-token SSM param name
  // (the raw token is fetched at runtime, never committed), and the non-secret
  // image/network-connector refs the control plane sends in the POST /microvms
  // run body. The lifetime values are the explicit AppTheory ProviderRunInput
  // MaximumDurationSeconds + ProviderIdlePolicy boundary from ADR 0010; Host
  // does not create a local scheduler or provider step machine for human gaps.
  // addEnvironment is the CDK-supported way to append env vars to a Function
  // constructed elsewhere.
  fn.addEnvironment("HOSTED_GENESIS_MICROVM_ENABLED", "true");
  fn.addEnvironment(
    "HOSTED_GENESIS_MICROVM_MAXIMUM_DURATION_SECONDS",
    String(HOSTED_GENESIS_MICROVM_MAXIMUM_DURATION_SECONDS),
  );
  fn.addEnvironment(
    "HOSTED_GENESIS_MICROVM_IDLE_MAX_SECONDS",
    String(HOSTED_GENESIS_MICROVM_IDLE_MAX_SECONDS),
  );
  fn.addEnvironment(
    "HOSTED_GENESIS_MICROVM_IDLE_SUSPENDED_SECONDS",
    String(HOSTED_GENESIS_MICROVM_IDLE_SUSPENDED_SECONDS),
  );
  fn.addEnvironment(
    "HOSTED_GENESIS_MICROVM_IDLE_AUTO_RESUME_ENABLED",
    String(HOSTED_GENESIS_MICROVM_IDLE_AUTO_RESUME_ENABLED),
  );
  fn.addEnvironment(
    "APPTHEORY_MICROVM_CONTROLLER_ENDPOINT",
    controllerEndpoint,
  );
  fn.addEnvironment(
    "HOSTED_GENESIS_MICROVM_AUTH_TOKEN_SSM_PARAM",
    authTokenSSMParamName,
  );
  fn.addEnvironment("APPTHEORY_MICROVM_IMAGE_REF", imageArn);
  fn.addEnvironment(
    "APPTHEORY_MICROVM_INGRESS_NETWORK_CONNECTOR_REFS",
    ingressConnectorArns.join(","),
  );
  fn.addEnvironment(
    "APPTHEORY_MICROVM_EGRESS_NETWORK_CONNECTOR_REFS",
    egressConnectorArns.join(","),
  );
  fn.addEnvironment(
    "APPTHEORY_MICROVM_NETWORK_CONNECTOR_REFS",
    egressConnectorArns.join(","),
  );
}

// ssmParamArn formats the full ARN for an SSM parameter name (the parameter is
// assumed to live in the current account + region). SSM parameter ARNs include
// the leading slash of the name verbatim.
function ssmParamArn(scope: Construct, paramName: string): string {
  const name = paramName.startsWith("/") ? paramName : `/${paramName}`;
  return `arn:aws:ssm:${cdk.Aws.REGION}:${cdk.Aws.ACCOUNT_ID}:parameter${name}`;
}

// hostedGenesisMicrovmAuthTokenHandler is the inline custom-resource Lambda that
// owns the authorizer bearer token lifecycle. It is the ONLY place the raw token
// exists at runtime. It:
//   - onCreate: generates 32 random bytes, hex-encodes them as the bearer token,
//     writes the RAW token to the deterministic SSM SecureString (Type=SecureString,
//     default alias/aws/ssm key), and returns ONLY
//     { AuthTokenSha256: "sha256:<hex>", AuthTokenSSMParamName: <paramName> }.
//   - onUpdate: re-gets the existing parameter and recomputes the digest. The
//     token is NOT rotated on stack updates — rotating it would invalidate every
//     running controller the control plane is dispatching to. The
//     recompute keeps the returned digest consistent with the stored value
//     without ever printing the raw token.
//   - onDelete: deletes the SSM parameter (only when removalPolicy is DESTROY;
//     the provider is not attached to a RETAIN resource for live, so no-op).
//
// Security invariants enforced here:
//   - The raw token is NEVER in the response Data, logs, or thrown errors. Only
//     the sha256 digest + param name are returned to CloudFormation.
//   - The SSM parameter is written as a SecureString (a plaintext Type is
//     rejected before writing).
//   - Logging is limited to param name + digest prefix (first 12 chars); the
//     raw token is never logged.
const hostedGenesisMicrovmAuthTokenHandler = `
const { SSMClient, PutParameterCommand, GetParameterCommand, DeleteParameterCommand } = require('@aws-sdk/client-ssm');
const crypto = require('crypto');

const REGION = process.env.AWS_REGION || process.env.AWS_DEFAULT_REGION || 'us-east-1';
const ssm = new SSMClient({ region: REGION });
const PARAM_NAME = process.env.AUTH_TOKEN_SSM_PARAM_NAME;
if (!PARAM_NAME) throw new Error('AUTH_TOKEN_SSM_PARAM_NAME env is required');

function sha256hex(value) {
  return crypto.createHash('sha256').update(value, 'utf8').digest('hex');
}

function digestPrefix(digest) {
  return digest.slice(0, 12);
}

exports.handler = async (event) => {
  const reqType = event.RequestType;
  try {
    if (reqType === 'Create') {
      const rawToken = crypto.randomBytes(32).toString('hex');
      await ssm.send(new PutParameterCommand({
        Name: PARAM_NAME,
        Value: rawToken,
        Type: 'SecureString',
        Overwrite: true,
        Description: 'CDK-owned hosted-genesis AppTheory MicroVM controller authorizer bearer token (P52 #873)',
        Tier: 'Standard',
      }));
      const digest = 'sha256:' + sha256hex(rawToken);
      console.log('hosted-genesis microvm auth-token created param=%s digest_prefix=%s', PARAM_NAME, digestPrefix(digest));
      return { Data: { AuthTokenSha256: digest, AuthTokenSSMParamName: PARAM_NAME } };
    }
    if (reqType === 'Update') {
      // Do NOT rotate the token on stack update — a rotation would invalidate
      // every running controller the control plane is dispatching to. Re-read
      // the stored value and recompute the digest so the returned value stays
      // consistent with the stored secret without ever printing the raw token.
      const res = await ssm.send(new GetParameterCommand({ Name: PARAM_NAME, WithDecryption: true }));
      const rawToken = (res.Parameter && res.Parameter.Value) || '';
      if (!rawToken) throw new Error('auth-token SSM parameter is empty on update');
      const digest = 'sha256:' + sha256hex(rawToken);
      console.log('hosted-genesis microvm auth-token re-read on update param=%s digest_prefix=%s', PARAM_NAME, digestPrefix(digest));
      return { Data: { AuthTokenSha256: digest, AuthTokenSSMParamName: PARAM_NAME } };
    }
    if (reqType === 'Delete') {
      try {
        await ssm.send(new DeleteParameterCommand({ Name: PARAM_NAME }));
        console.log('hosted-genesis microvm auth-token deleted param=%s', PARAM_NAME);
      } catch (err) {
        // Idempotent: a missing parameter on delete is success, not a failure.
        console.log('hosted-genesis microvm auth-token delete no-op param=%s err=%s', PARAM_NAME, String(err && err.name || err));
      }
      return { Data: { AuthTokenSSMParamName: PARAM_NAME } };
    }
    throw new Error('unsupported RequestType: ' + reqType);
  } catch (err) {
    // Never include the raw token in the error message. Only the param name +
    // digest prefix are safe to surface; the raw token never enters Data/logs.
    console.log('hosted-genesis microvm auth-token handler error param=%s err=%s', PARAM_NAME, String(err && err.message || err));
    throw err;
  }
};
`;

// HostedGenesisMicrovmAuthTokenProvisioning is the CDK-owned authorizer bearer
// token provisioning result. authTokenSha256 is the sha256:<hex> digest (a
// CloudFormation token from the custom resource's getAtt — never a literal raw
// token or a literal hash). paramName is the deterministic SSM SecureString
// name the control plane loads the raw token from at runtime.
interface HostedGenesisMicrovmAuthTokenProvisioning {
  readonly authTokenSha256: string;
  readonly paramName: string;
}

// provisionHostedGenesisMicrovmAuthToken creates the CDK-owned custom resource
// that generates the hosted-genesis AppTheory MicroVM controller authorizer
// bearer token. The raw token exists only in the custom-resource Lambda runtime
// and the deterministic SSM SecureString value; only the sha256 digest + param
// name return to CloudFormation. This replaces the prior manual
// `aws ssm put-parameter` operator step + the two CDK context values that
// backed it (hostedGenesisMicrovmAuthorizerTokenSha256 +
// hostedGenesisMicrovmAuthTokenSSMParamName).
//
// The custom resource is a Lambda-backed Provider (customresources.Provider +
// an inline Node 20 handler). The handler is inline (no external asset) so the
// raw-token lifecycle stays entirely in this file's review surface and never
// touches a separately-built artifact. The provider's role is granted
// ssm:PutParameter + ssm:GetParameter + ssm:DeleteParameter + kms:Decrypt on
// the deterministic param only — no wildcard SSM, no other params. The
// SecureString uses the default alias/aws/ssm key (account/region-scoped), so
// kms:Decrypt is scoped ViaService to SSM in the deploy region.
//
// removalPolicy: when DESTROY (lab / dev), stack deletion deletes the SSM param
// (the handler's Delete branch runs). When RETAIN (live), the custom resource
// is retained with the stack so the param survives — the handler's Delete
// branch does not run and the raw token persists for the lifetime of the live
// deployment. Either way the raw token is never in CloudFormation.
function provisionHostedGenesisMicrovmAuthToken(
  scope: Construct,
  id: string,
  props: {
    readonly stage: string;
    readonly paramName: string;
    readonly removalPolicy: cdk.RemovalPolicy;
  },
): HostedGenesisMicrovmAuthTokenProvisioning {
  const paramArn = ssmParamArn(scope, props.paramName);

  const handler = new lambda.Function(scope, `${id}Handler`, {
    functionName: `${props.stage}-hosted-genesis-microvm-auth-token-provisioner`,
    description:
      "CDK-owned hosted-genesis MicroVM controller authorizer bearer token generator (P52 #873)",
    runtime: lambda.Runtime.NODEJS_20_X,
    handler: "index.handler",
    code: lambda.Code.fromInline(hostedGenesisMicrovmAuthTokenHandler),
    memorySize: 256,
    timeout: cdk.Duration.seconds(30),
    environment: {
      AUTH_TOKEN_SSM_PARAM_NAME: props.paramName,
    },
  });

  // Least-privilege SSM grants on the deterministic auth-token param only.
  handler.addToRolePolicy(
    new iam.PolicyStatement({
      sid: "ManageAuthTokenSSMParameter",
      actions: [
        "ssm:PutParameter",
        "ssm:GetParameter",
        "ssm:GetParameters",
        "ssm:DeleteParameter",
      ],
      resources: [paramArn],
    }),
  );
  // kms:Decrypt for the SecureString encryption, scoped ViaService to SSM in the
  // deploy region. The default alias/aws/ssm key is account/region-scoped, so
  // resource "*" + the ViaService condition is the least-priv grant for
  // decrypt-only-for-SSM without over-granting kms:Decrypt generally.
  handler.addToRolePolicy(
    new iam.PolicyStatement({
      sid: "DecryptAuthTokenSSMParameter",
      actions: ["kms:Decrypt"],
      resources: ["*"],
      conditions: {
        StringEquals: {
          "kms:ViaService": `ssm.${cdk.Aws.REGION}.amazonaws.com`,
        },
      },
    }),
  );

  // The custom-resource provider. The Provider framework wires the Lambda into a
  // stable CustomResource and surfaces the handler's returned Data as getAtt
  // tokens. removalPolicy propagates to the underlying custom resource so a
  // DESTROY stack deletes the SSM param and a RETAIN stack keeps it.
  const provider = new customresources.Provider(scope, `${id}Provider`, {
    onEventHandler: handler,
  });

  const resource = new cdk.CustomResource(scope, id, {
    serviceToken: provider.serviceToken,
    removalPolicy: props.removalPolicy,
    properties: {
      // The param name is the only non-secret input. It is also emitted as the
      // stable property set; changing it would recreate the resource (which is
      // the correct behavior — a new param name means a new token).
      AuthTokenSSMParamName: props.paramName,
      Stage: props.stage,
    },
  });

  // The handler returns ONLY the digest + param name. authTokenSha256 is a
  // CloudFormation getAtt token (Fn::GetAtt), never a literal raw token or a
  // literal hash — it resolves at deploy time to the sha256 of the generated
  // token and is wired into authorizer + controller env.
  const authTokenSha256 = cdk.Token.asString(
    resource.getAtt("AuthTokenSha256"),
  );

  return {
    authTokenSha256,
    paramName: props.paramName,
  };
}

// createHostedGenesisMicrovmImageBuildRole creates the IAM role passed to
// AWS::Lambda::MicrovmImage as BuildRoleArn. The MicroVM image build service
// (lambda.amazonaws.com) assumes it; it can fetch the repo-built
// workload code artifact from the CDK asset staging bucket and build/delete the
// MicroVM image. Permissions are scoped to this image's artifacts only — no
// broader account access, no wildcard s3:GetObject across all buckets. This
// eliminates the prior hostedGenesisMicrovmBuildRoleArn hand-context value.
function createHostedGenesisMicrovmImageBuildRole(
  scope: Construct,
  id: string,
  namePrefix: string,
  stage: string,
  workloadArtifact: s3assets.Asset,
): iam.Role {
  const role = new iam.Role(scope, id, {
    roleName: `${namePrefix}-hosted-genesis-microvm-image-build`,
    description:
      "Build role for the hosted-genesis AppTheory MicroVM image (fetch code artifact + build image)",
    // The MicroVM image build service assumes this role. AWS Lambda MicroVM
    // docs specify lambda.amazonaws.com as the trust principal; the
    // microvms.lambda.amazonaws.com form is rejected by IAM as an invalid
    // principal (CREATE fails with "IAM Invalid principal in policy").
    assumedBy: new iam.ServicePrincipal("lambda.amazonaws.com"),
  });

  // Fetch the workload code artifact tarball from the CDK asset staging bucket.
  // Scoped to this asset's bucket + key prefix only.
  role.addToPolicy(
    new iam.PolicyStatement({
      sid: "ReadWorkloadCodeArtifact",
      actions: ["s3:GetObject"],
      resources: [
        workloadArtifact.bucket.bucketArn,
        `${workloadArtifact.bucket.bucketArn}/*`,
      ],
    }),
  );

  // MicroVM image build/delete actions scoped to this stack's MicroVM images.
  // Lambda's MicrovmImage build needs Create/Get/DeleteMicrovmImage plus
  // GetMicrovmImageVersion to poll the asynchronous build to CREATED.
  role.addToPolicy(
    new iam.PolicyStatement({
      sid: "BuildMicrovmImage",
      actions: [
        "lambda:CreateMicrovmImage",
        "lambda:GetMicrovmImage",
        "lambda:DeleteMicrovmImage",
        "lambda:GetMicrovmImageVersion",
      ],
      resources: [
        cdk.Stack.of(scope).formatArn({
          service: "lambda",
          resource: "microvm-image",
          resourceName: "*",
          arnFormat: cdk.ArnFormat.SLASH_RESOURCE_NAME,
        }),
      ],
    }),
  );

  // P52 H1: CloudWatch Logs permissions for the image build. The MicroVM image
  // build service writes build logs to CloudWatch when logging is enabled (the
  // logging.cloudWatch config on AppTheoryMicrovmImage above). The AWS Lambda
  // MicroVM getting-started IAM example grants the build role
  // logs:CreateLogGroup / logs:CreateLogStream / logs:PutLogEvents on
  // arn:aws:logs:*:*:* (microvms-getting-started.html "Prerequisites"). Without
  // these the build cannot emit logs, so a failing build is undiagnosable —
  // exactly the 2026-07-04 failure. Scoped to CloudWatch Logs only (logs:*
  // wildcard resource, matching the documented example); no other service is
  // touched. The trust principal (lambda.amazonaws.com) and the MicroVM image
  // actions above are unchanged.
  role.addToPolicy(
    new iam.PolicyStatement({
      sid: "WriteMicrovmImageBuildLogs",
      actions: [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
      ],
      resources: ["arn:aws:logs:*:*:*"],
    }),
  );

  // Tag the role for traceability.
  cdk.Tags.of(role).add("Service", "lesser-host");
  cdk.Tags.of(role).add("Stage", stage);
  cdk.Tags.of(role).add("Purpose", "hosted-genesis-microvm-image-build");

  return role;
}

// hostedGenesisMicrovmProviderKeySSMParams are the SSM SecureString parameter
// NAMES the in-VM workload's SSM fallback reads for provider API keys. They
// mirror internal/secrets.OpenAIServiceSSMParameterName and ClaudeSSMParameterName
// exactly (unscoped — the control plane reads the same params). Only the NAMES
// are referenced here; the raw key VALUES are never in CDK, the image env, or
// CloudFormation — the execution role gets ssm:GetParameter on these specific
// ARNs and the workload loads them at runtime. Keep in sync with
// internal/secrets/keys.go if those paths change.
const hostedGenesisMicrovmProviderKeySSMParams = [
  "/lesser-host/api/openai/service",
  "/lesser-host/api/claude",
] as const;

// createHostedGenesisMicrovmExecutionRole creates the host-owned IAM role passed
// to RunMicrovm as the MicroVM execution role (AppTheory executionRole
// propagation). AWS Lambda MicroVMs assume it via
// lambda.amazonaws.com trust for the in-VM hosted-genesis workload.
//
// Least-privilege — exactly what the in-VM workload needs to run a turn:
//   - DynamoDB read/write on the Host state table only (the workload persists
//     HostedGenesisSession completion truth via store.MicroVMInit + STATE_TABLE_NAME).
//   - ssm:GetParameter on the two provider-key SecureString params (the workload's
//     SSM key fallback). Scoped to those ARNs only — no broader ssm:*.
//   - kms:Decrypt for the SecureString encryption (scoped ViaService to SSM in
//     the current region). The default SSM KMS key is account/region-scoped, so
//     the resource is the default key ARN pattern; the ViaService condition
//     constrains decrypt to SSM use only.
//   - X-Ray/CloudWatch emission for the in-VM process observability.
//
// Deliberately absent: wildcard DynamoDB, wildcard SSM, iam:PassRole, any IAM
// mutation, secretsmanager:*, any cross-tenant resource access. Raw secret
// values never enter the image env or CloudFormation output.
function createHostedGenesisMicrovmExecutionRole(
  scope: Construct,
  id: string,
  namePrefix: string,
  stage: string,
  stateTable: dynamodb.ITable,
): iam.Role {
  const role = new iam.Role(scope, id, {
    roleName: `${namePrefix}-hosted-genesis-microvm-execution`,
    description:
      "Execution role for the in-VM hosted-genesis MicroVM workload (Host state R/W + SSM provider keys)",
    // AWS Lambda MicroVMs assume this role via lambda.amazonaws.com trust
    // (microvms.lambda.amazonaws.com is rejected by IAM as an invalid
    // principal — see the build role comment above).
    assumedBy: new iam.ServicePrincipal("lambda.amazonaws.com"),
  });

  // DynamoDB read/write on the Host state table only. The workload reads
  // HostedGenesisSession truth and persists completion (assistant_turn_ready /
  // declaration_ready). grantReadWriteData covers GetItem/PutItem/UpdateItem/
  // Query/Scan/BatchWrite scoped to the table + its indexes.
  stateTable.grantReadWriteData(role);

  // ssm:GetParameter on the two provider-key SecureString params only. No
  // wildcard, no ssm:PutParameter, no other params. The workload's SSM fallback
  // reads these at runtime; raw values never reach the image env.
  role.addToPolicy(
    new iam.PolicyStatement({
      sid: "ReadProviderKeySSMParams",
      actions: ["ssm:GetParameter"],
      resources: hostedGenesisMicrovmProviderKeySSMParams.map((name) =>
        ssmParamArn(scope, name),
      ),
    }),
  );

  // kms:Decrypt for the SecureString encryption, constrained to SSM use via
  // ViaService. The SecureString params use the default SSM KMS key
  // (alias/aws/ssm); its ARN is account/region-scoped, so resource "*" with the
  // ViaService condition is the least-priv way to grant decrypt-only-for-SSM
  // without over-granting kms:Decrypt generally.
  role.addToPolicy(
    new iam.PolicyStatement({
      sid: "DecryptProviderKeySSMParams",
      actions: ["kms:Decrypt"],
      resources: ["*"],
      conditions: {
        StringEquals: {
          "kms:ViaService": `ssm.${cdk.Aws.REGION}.amazonaws.com`,
        },
      },
    }),
  );

  // X-Ray trace emission + CloudWatch Logs for the in-VM process observability
  // (the workload wires apptheory observability hooks). Scoped managed policies
  // only — no administrative actions.
  role.addManagedPolicy(
    iam.ManagedPolicy.fromAwsManagedPolicyName(
      "service-role/AWSLambdaBasicExecutionRole",
    ),
  );

  cdk.Tags.of(role).add("Service", "lesser-host");
  cdk.Tags.of(role).add("Stage", stage);
  cdk.Tags.of(role).add("Purpose", "hosted-genesis-microvm-execution");

  return role;
}

function deployedStage(stage: string): boolean {
  const normalized = stage.trim().toLowerCase();
  return normalized === "lab" || normalized === "live";
}

function devTestOptOut(scope: Construct, stage: string): boolean {
  if (!contextBoolean(scope, contextKeys.devTestOptOut)) {
    return false;
  }
  if (deployedStage(stage)) {
    throw new Error(
      `${contextKeys.devTestOptOut} is dev/test-only and cannot be used for deployed stage ${stage}; the hosted-genesis MicroVM path is CDK-owned and required for deployed stages`,
    );
  }
  return true;
}

function contextBoolean(scope: Construct, key: string): boolean {
  const raw = scope.node.tryGetContext(key);
  if (typeof raw === "boolean") return raw;
  if (typeof raw !== "string") return false;
  return raw.trim().toLowerCase() === "true";
}

function buildGoBootstrapAsset(
  repoRoot: string,
  id: string,
  entry: string,
): lambda.Code {
  const buildDir = path.join(repoRoot, "cdk", ".build", id);
  fs.mkdirSync(buildDir, { recursive: true });
  execFileSync("go", ["build", "-o", path.join(buildDir, "bootstrap"), entry], {
    cwd: repoRoot,
    stdio: "inherit",
    env: {
      ...process.env,
      CGO_ENABLED: "0",
      GOOS: "linux",
      GOARCH: "amd64",
    },
  });
  return lambda.Code.fromAsset(buildDir);
}

// buildHostedGenesisMicrovmWorkloadAsset builds the in-VM hosted-genesis
// workload entrypoint (cmd/hosted-genesis-microvm-workload) for the MicroVM
// image's linux/arm64 runtime and packages it as a CDK S3 asset. The returned
// asset's s3ObjectUrl is the AppTheoryMicrovmImage codeArtifact.uri — a
// repo-built artifact, not an external CDK context value (kills G4).
//
// P52 H1: the AWS::Lambda::MicrovmImage code artifact zip MUST contain a
// Dockerfile alongside the application artifacts. AWS Lambda MicroVM developer
// guide (microvms-images.html): "you provide a zip package that contains a
// Dockerfile and your application artifacts, which you upload to Amazon S3.
// Your Dockerfile defines how your application is packaged. Lambda builds your
// application container image by running your Dockerfile on top of an operating
// system environment that is provided by a Lambda-managed MicroVM base image."
// The 2026-07-04 lab deploy failed with HostedGenesisMicrovmImage CREATE_FAILED
// "did not stabilize" precisely because the asset zip contained ONLY the binary
// — no Dockerfile — so Lambda's build had nothing to run and the image build
// transitioned to FAILED (~55s) with no diagnosable logs (logging was disabled).
//
// The Dockerfile's FROM is the CONTAINER base image (distinct from the MicroVM
// base image set via baseImageArn — see HOSTED_GENESIS_MICROVM_BASE_IMAGE_ARN).
// The AWS Lambda MicroVM developer guide getting-started example
// (microvms-getting-started.html Step 1) uses a PLAIN container base
// (`FROM node:24-alpine`) and the docs state: "The FROM instruction sets the
// container image for your application layers. You can use any compatible
// container image. The Lambda managed base image ... is specified separately
// with --base-image-arn." The prior FROM public.ecr.aws/lambda/microvms:al2023-minimal
// was the only remaining difference from that working plain-base pattern, and
// the lab deploy (deploy #10) showed the app listening on :8080 with zero
// inbound TCP connections from the build service — al2023-minimal appears to
// prevent the Lambda MicroVM build service from routing inbound HTTP to the
// container's :8080 hook port. Switch to alpine:3.20 to match the
// getting-started's working plain-base pattern. The binary is a static
// linux/arm64 Go binary (CGO_ENABLED=0, statically linked, no libc dependency)
// that serves the M16 lifecycle hooks on port 8080 (hooks.port=8080), so it
// runs on alpine (musl) without issue; Lambda launches it via the CMD
// instruction (microvms-images.html: "Launches your application using the
// ENTRYPOINT or CMD instruction"; getting-started Step 1 uses
// `CMD ["node", "app.js"]`).
//
// s3assets.Asset packages the entire buildDir directory, so writing the
// Dockerfile into buildDir alongside the binary makes the uploaded zip contain
// binary + Dockerfile — the shape AWS requires. The Dockerfile is generated
// (not committed) so it stays in sync with the binary name + port and never
// drifts from the build step that produces the binary.
function buildHostedGenesisMicrovmWorkloadAsset(
  scope: Construct,
  id: string,
  repoRoot: string,
): s3assets.Asset {
  const buildDir = path.join(repoRoot, "cdk", ".build", id);
  fs.mkdirSync(buildDir, { recursive: true });
  const binaryPath = path.join(buildDir, "hosted-genesis-microvm-workload");
  execFileSync(
    "go",
    ["build", "-o", binaryPath, "./cmd/hosted-genesis-microvm-workload"],
    {
      cwd: repoRoot,
      stdio: "inherit",
      env: {
        ...process.env,
        CGO_ENABLED: "0",
        GOOS: "linux",
        GOARCH: "arm64",
      },
    },
  );
  // Write the Dockerfile into the same buildDir s3assets.Asset packages, so the
  // code artifact zip contains the binary + Dockerfile. FROM a plain container
  // base (alpine:3.20) matching the AWS getting-started's working plain-base
  // pattern (node:24-alpine); CMD launches the static Go binary that serves the
  // M16 lifecycle hooks on port 8080. See the function-level comment for why
  // al2023-minimal was replaced.
  const dockerfileContent = [
    "# P52 H1: Lambda MicroVM image code artifact Dockerfile. Generated by",
    "# cdk/lib/hosted-genesis-microvm.ts buildHostedGenesisMicrovmWorkloadAsset;",
    "# do not edit by hand. The FROM is the CONTAINER base image (distinct from",
    "# the MicroVM base image set via baseImageArn). alpine:3.20 matches the AWS",
    "# getting-started's working plain-base pattern (node:24-alpine); the prior",
    "# al2023-minimal base appeared to prevent the build service from reaching",
    "# the container's :8080 hook port. The Go binary is static (CGO_ENABLED=0).",
    "FROM alpine:3.20",
    "WORKDIR /app",
    "COPY hosted-genesis-microvm-workload /app/hosted-genesis-microvm-workload",
    "EXPOSE 8080",
    'CMD ["/app/hosted-genesis-microvm-workload"]',
    "",
  ].join("\n");
  fs.writeFileSync(
    path.join(buildDir, "Dockerfile"),
    dockerfileContent,
    "utf8",
  );
  return new s3assets.Asset(scope, id, { path: buildDir });
}
