export function renderProvisionRunnerPreBuildCommands(): string {
	return [
		'set -euo pipefail',
		'echo "Assuming role into target account..."',
		'if [ -n "${MANAGED_ORG_VENDING_ROLE_ARN:-}" ]; then',
		'  echo "Assuming org vending role..."',
		'  ORG_CREDS=$(aws sts assume-role --role-arn "$MANAGED_ORG_VENDING_ROLE_ARN" --role-session-name "lesser-host-org-$APP_SLUG" --duration-seconds 3600 --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text)',
		'  read ORG_AK ORG_SK ORG_TOKEN <<< "$ORG_CREDS"',
		'  CREDS=$(AWS_ACCESS_KEY_ID=$ORG_AK AWS_SECRET_ACCESS_KEY=$ORG_SK AWS_SESSION_TOKEN=$ORG_TOKEN aws sts assume-role --role-arn "arn:aws:iam::$TARGET_ACCOUNT_ID:role/$TARGET_ROLE_NAME" --role-session-name "lesser-host-$APP_SLUG" --duration-seconds 3600 --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text)',
		'else',
		'  CREDS=$(aws sts assume-role --role-arn "arn:aws:iam::$TARGET_ACCOUNT_ID:role/$TARGET_ROLE_NAME" --role-session-name "lesser-host-$APP_SLUG" --duration-seconds 3600 --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" --output text)',
		'fi',
		'read MANAGED_AK MANAGED_SK MANAGED_TOKEN <<< "$CREDS"',
		'mkdir -p ~/.aws',
		'printf "[managed]\\naws_access_key_id=%s\\naws_secret_access_key=%s\\naws_session_token=%s\\n" "$MANAGED_AK" "$MANAGED_SK" "$MANAGED_TOKEN" > ~/.aws/credentials',
		'printf "[profile managed]\\nregion=%s\\noutput=json\\n" "$TARGET_REGION" > ~/.aws/config',
		'aws sts get-caller-identity --profile managed',
	].join('\n');
}

export function renderProvisionRunnerBuildCommands(): string {
	return [
		'set -euo pipefail',
		'RUN_MODE="${RUN_MODE:-lesser}"',
		'OWNER="${GITHUB_OWNER:-equaltoai}"',
		'REPO="${GITHUB_REPO:-lesser}"',
		'TAG="${LESSER_VERSION:-}"',
		'fail() { echo "ERROR: $1" >&2; exit 1; }',
		'resolve_latest_release_tag() {',
		'  o="$1"',
		'  r="$2"',
		'  url=$(curl -sSfL -o /dev/null -w "%{url_effective}" "https://github.com/$o/$r/releases/latest")',
		'  echo "${url##*/}"',
		'}',
		'download_github_release_asset() {',
		'  o="$1"',
		'  r="$2"',
		'  tag="$3"',
		'  asset="$4"',
		'  out="$5"',
		'  url="https://github.com/$o/$r/releases/download/$tag/$asset"',
		'  echo "Downloading $asset from $o/$r@$tag..."',
		'  if [ -n "${GITHUB_TOKEN:-}" ]; then',
		'    curl -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/octet-stream" -sSfL -o "$out" "$url"',
		'  else',
		'    curl -sSfL -o "$out" "$url"',
		'  fi',
		'}',
		'download_github_tag_archive() {',
		'  o="$1"',
		'  r="$2"',
		'  tag="$3"',
		'  out="$4"',
		'  url="https://github.com/$o/$r/archive/refs/tags/$tag.tar.gz"',
		'  echo "Downloading source archive for $o/$r@$tag..."',
		'  if [ -n "${GITHUB_TOKEN:-}" ]; then',
		'    curl -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/octet-stream" -sSfL -o "$out" "$url"',
		'  else',
		'    curl -sSfL -o "$out" "$url"',
		'  fi',
		'}',
		'checksum_for_asset() {',
		'  checksums_path="$1"',
		'  asset_name="$2"',
		"  awk -v asset=\"$asset_name\" '{ name=$2; sub(/^\\*/, \"\", name); if (name == asset) { print $1; exit } }' \"$checksums_path\"",
		'}',
		'verify_downloaded_asset_checksum() {',
		'  checksums_path="$1"',
		'  asset_name="$2"',
		'  file_path="$3"',
		'  expected=$(checksum_for_asset "$checksums_path" "$asset_name")',
		'  test -n "$expected" || fail "checksum entry missing for $asset_name"',
		"  actual=$(sha256sum \"$file_path\" | awk '{print $1}')",
		'  test "$expected" = "$actual" || fail "checksum mismatch for $asset_name"',
		'}',
		'prepare_lesser_release_dir() {',
		'  release_dir="$1"',
		'  rm -rf "$release_dir"',
		'  mkdir -p "$release_dir"',
		'  download_github_release_asset "$OWNER" "$REPO" "$TAG" "checksums.txt" "$release_dir/checksums.txt"',
		'  download_github_release_asset "$OWNER" "$REPO" "$TAG" "lesser-release.json" "$release_dir/lesser-release.json"',
		'  download_github_release_asset "$OWNER" "$REPO" "$TAG" "lesser-lambda-bundle.tar.gz" "$release_dir/lesser-lambda-bundle.tar.gz"',
		'  download_github_release_asset "$OWNER" "$REPO" "$TAG" "lesser-lambda-bundle.json" "$release_dir/lesser-lambda-bundle.json"',
		'  verify_downloaded_asset_checksum "$release_dir/checksums.txt" "lesser-release.json" "$release_dir/lesser-release.json"',
		'  verify_downloaded_asset_checksum "$release_dir/checksums.txt" "lesser-lambda-bundle.tar.gz" "$release_dir/lesser-lambda-bundle.tar.gz"',
		'  verify_downloaded_asset_checksum "$release_dir/checksums.txt" "lesser-lambda-bundle.json" "$release_dir/lesser-lambda-bundle.json"',
		'  LESSER_RELEASE_NAME=$(jq -r \'.name // empty\' "$release_dir/lesser-release.json")',
		'  test "$LESSER_RELEASE_NAME" = "lesser" || fail "unexpected Lesser release manifest name: $LESSER_RELEASE_NAME"',
		'  LESSER_RELEASE_VERSION=$(jq -r \'.version // empty\' "$release_dir/lesser-release.json")',
		'  test "$LESSER_RELEASE_VERSION" = "$TAG" || fail "Lesser release manifest version mismatch: $LESSER_RELEASE_VERSION"',
		'  LESSER_BUNDLE_PATH=$(jq -r \'.artifacts.deploy_artifacts.lambda_bundle.path // empty\' "$release_dir/lesser-release.json")',
		'  test "$LESSER_BUNDLE_PATH" = "lesser-lambda-bundle.tar.gz" || fail "unexpected Lesser lambda bundle path: $LESSER_BUNDLE_PATH"',
		'  LESSER_BUNDLE_MANIFEST_PATH=$(jq -r \'.artifacts.deploy_artifacts.lambda_bundle.manifest_path // empty\' "$release_dir/lesser-release.json")',
		'  test "$LESSER_BUNDLE_MANIFEST_PATH" = "lesser-lambda-bundle.json" || fail "unexpected Lesser lambda bundle manifest path: $LESSER_BUNDLE_MANIFEST_PATH"',
		'}',
		'install_lesser_lambda_bundle() {',
		'  release_dir="$1"',
		'  asset_root="$2"',
		'  bundle_manifest_path="$release_dir/lesser-lambda-bundle.json"',
		'  bundle_path="$release_dir/lesser-lambda-bundle.tar.gz"',
		'  bundle_kind=$(jq -r \'.kind // empty\' "$bundle_manifest_path")',
		'  test "$bundle_kind" = "lesser.lambda_bundle_manifest" || fail "unexpected Lesser lambda bundle manifest kind: $bundle_kind"',
		'  bundle_manifest_schema=$(jq -r \'.schema_version // empty\' "$bundle_manifest_path")',
		'  test "$bundle_manifest_schema" = "1" || fail "unsupported Lesser lambda bundle schema: $bundle_manifest_schema"',
		'  manifest_bundle_path=$(jq -r \'.bundle.path // empty\' "$bundle_manifest_path")',
		'  test "$manifest_bundle_path" = "lesser-lambda-bundle.tar.gz" || fail "unexpected Lesser lambda bundle archive path: $manifest_bundle_path"',
		'  bundle_sha=$(jq -r \'.bundle.sha256 // empty\' "$bundle_manifest_path")',
		'  test -n "$bundle_sha" || fail "missing Lesser lambda bundle checksum"',
		"  actual_bundle_sha=$(sha256sum \"$bundle_path\" | awk '{print $1}')",
		'  test "$bundle_sha" = "$actual_bundle_sha" || fail "Lesser lambda bundle checksum mismatch"',
		'  rm -rf "$asset_root"',
		'  mkdir -p "$asset_root"',
		'  tar -xzf "$bundle_path" -C "$asset_root"',
		'  (',
		'    cd "$asset_root"',
		'    jq -r \'.files[] | "\\(.sha256)  \\(.path)"\' "$bundle_manifest_path" > .lambda-bundle.checksums',
		'    sha256sum -c .lambda-bundle.checksums',
		'    rm -f .lambda-bundle.checksums',
		'  )',
		'  release_version=$(jq -r \'.version // empty\' "$release_dir/lesser-release.json")',
		'  release_git_sha=$(jq -r \'.git_sha // empty\' "$release_dir/lesser-release.json")',
		'  bundle_files=$(jq -c \'[.files[].path]\' "$bundle_manifest_path")',
		'  prepared_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")',
		'  jq -n --arg mode "release" --arg version "$release_version" --arg git_sha "$release_git_sha" --arg prepared_at "$prepared_at" --argjson files "$bundle_files" \'{schema:1,mode:$mode,files:$files,release_version:$version,release_git_sha:$git_sha,prepared_at:$prepared_at}\' > "$asset_root/metadata.json"',
		'}',
		'prepare_lesser_body_release_dir() {',
		'  body_release_dir="$1"',
		'  body_owner="$2"',
		'  body_repo="$3"',
		'  body_tag="$4"',
		'  body_stage="$5"',
		'  rm -rf "$body_release_dir"',
		'  mkdir -p "$body_release_dir"',
		'  download_github_release_asset "$body_owner" "$body_repo" "$body_tag" "checksums.txt" "$body_release_dir/checksums.txt"',
		'  download_github_release_asset "$body_owner" "$body_repo" "$body_tag" "lesser-body-release.json" "$body_release_dir/lesser-body-release.json"',
		'  download_github_release_asset "$body_owner" "$body_repo" "$body_tag" "lesser-body-deploy.json" "$body_release_dir/lesser-body-deploy.json"',
		'  download_github_release_asset "$body_owner" "$body_repo" "$body_tag" "deploy-lesser-body-from-release.sh" "$body_release_dir/deploy-lesser-body-from-release.sh"',
		'  download_github_release_asset "$body_owner" "$body_repo" "$body_tag" "lesser-body.zip" "$body_release_dir/lesser-body.zip"',
		'  download_github_release_asset "$body_owner" "$body_repo" "$body_tag" "lesser-body-managed-$body_stage.template.json" "$body_release_dir/lesser-body-managed-$body_stage.template.json"',
		'  chmod +x "$body_release_dir/deploy-lesser-body-from-release.sh"',
		'  verify_downloaded_asset_checksum "$body_release_dir/checksums.txt" "lesser-body-release.json" "$body_release_dir/lesser-body-release.json"',
		'  verify_downloaded_asset_checksum "$body_release_dir/checksums.txt" "lesser-body-deploy.json" "$body_release_dir/lesser-body-deploy.json"',
		'  verify_downloaded_asset_checksum "$body_release_dir/checksums.txt" "deploy-lesser-body-from-release.sh" "$body_release_dir/deploy-lesser-body-from-release.sh"',
		'  verify_downloaded_asset_checksum "$body_release_dir/checksums.txt" "lesser-body.zip" "$body_release_dir/lesser-body.zip"',
		'  verify_downloaded_asset_checksum "$body_release_dir/checksums.txt" "lesser-body-managed-$body_stage.template.json" "$body_release_dir/lesser-body-managed-$body_stage.template.json"',
		'  BODY_RELEASE_NAME=$(jq -r \'.name // empty\' "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_RELEASE_NAME" = "lesser-body" || fail "unexpected lesser-body release manifest name: $BODY_RELEASE_NAME"',
		'  BODY_RELEASE_VERSION=$(jq -r \'.version // empty\' "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_RELEASE_VERSION" = "$body_tag" || fail "lesser-body release manifest version mismatch: $BODY_RELEASE_VERSION"',
		'  BODY_DEPLOY_MANIFEST=$(jq -r \'.deploy.manifest_path // empty\' "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_DEPLOY_MANIFEST" = "lesser-body-deploy.json" || fail "unexpected lesser-body deploy manifest path: $BODY_DEPLOY_MANIFEST"',
		'  BODY_SOURCE_CHECKOUT_REQUIRED=$(jq -r \'.deploy.source_checkout_required // empty\' "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_SOURCE_CHECKOUT_REQUIRED" = "false" || fail "lesser-body release unexpectedly requires a source checkout"',
		'  BODY_NPM_INSTALL_REQUIRED=$(jq -r \'.deploy.npm_install_required // empty\' "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_NPM_INSTALL_REQUIRED" = "false" || fail "lesser-body release unexpectedly requires npm install"',
		'  BODY_TEMPLATE_PATH=$(jq -r ".artifacts.deploy_templates[$body_stage].path // empty" "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_TEMPLATE_PATH" = "lesser-body-managed-$body_stage.template.json" || fail "unexpected lesser-body template path for stage $body_stage: $BODY_TEMPLATE_PATH"',
		'  BODY_SCRIPT_PATH=$(jq -r \'.artifacts.deploy_script.path // empty\' "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_SCRIPT_PATH" = "deploy-lesser-body-from-release.sh" || fail "unexpected lesser-body deploy script path: $BODY_SCRIPT_PATH"',
		'  BODY_LAMBDA_PATH=$(jq -r \'.artifacts.lambda_zip.path // empty\' "$body_release_dir/lesser-body-release.json")',
		'  test "$BODY_LAMBDA_PATH" = "lesser-body.zip" || fail "unexpected lesser-body lambda zip path: $BODY_LAMBDA_PATH"',
		'}',
		'TAG_NORMALIZED=$(printf "%s" "$TAG" | tr "[:upper:]" "[:lower:]")',
		'if [ -z "$TAG" ] || [ "$TAG_NORMALIZED" = "latest" ]; then',
		'  echo "Resolving latest Lesser release..."',
		'  TAG=$(resolve_latest_release_tag "$OWNER" "$REPO")',
		'fi',
		'test -n "$TAG"',
		'test "$TAG" != "null"',
		'echo "Using Lesser release: $TAG"',
		'LESSER_RELEASE_DIR="$(pwd)/lesser-release"',
		'prepare_lesser_release_dir "$LESSER_RELEASE_DIR"',
		'download_github_tag_archive "$OWNER" "$REPO" "$TAG" lesser-src.tgz"',
		'rm -rf lesser-src && mkdir -p lesser-src && tar -xzf lesser-src.tgz --strip-components=1 -C lesser-src',
		'ARCH=$(uname -m)',
		'if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "amd64" ]; then BIN_NAME="lesser-linux-amd64"; fi',
		'if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then BIN_NAME="lesser-linux-arm64"; fi',
		'test -n "${BIN_NAME:-}"',
		'download_github_release_asset "$OWNER" "$REPO" "$TAG" "$BIN_NAME" "lesser-src/lesser"',
		'verify_downloaded_asset_checksum "$LESSER_RELEASE_DIR/checksums.txt" "$BIN_NAME" "lesser-src/lesser"',
		'chmod +x lesser-src/lesser',
		'cd lesser-src',
		'GO_TOOLCHAIN=$(grep "^toolchain " go.mod | awk \'{print $2}\' || true)',
		'GO_VERSION="${GO_TOOLCHAIN#go}"',
		'if [ -z "$GO_VERSION" ]; then GO_VERSION=$(grep "^go " go.mod | awk \'{print $2}\'); fi',
		'test -n "$GO_VERSION"',
		'GO_ARCH="amd64"',
		'if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then GO_ARCH="arm64"; fi',
		'echo "Installing Go toolchain: $GO_VERSION (linux-$GO_ARCH)"',
		'curl -sSfL -o go.tgz "https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz"',
		'rm -rf /usr/local/go && tar -C /usr/local -xzf go.tgz',
		'export PATH="/usr/local/go/bin:$PATH"',
		'go version',
		'STATE_DIR="$HOME/.lesser/$APP_SLUG/$BASE_DOMAIN"',
		'mkdir -p "$STATE_DIR"',
		'aws s3 cp "s3://$ARTIFACT_BUCKET/$BOOTSTRAP_S3_KEY" "$STATE_DIR/bootstrap.json" 2>/dev/null || true',
		'CONSENT_MESSAGE=""',
		'if [ -n "${CONSENT_MESSAGE_B64:-}" ]; then CONSENT_MESSAGE=$(printf "%s" "$CONSENT_MESSAGE_B64" | base64 --decode); fi',
		'PROVISION_INPUT="$STATE_DIR/provision.json"',
		': "${LESSER_HOST_URL:?LESSER_HOST_URL is required}"',
		'LESSER_HOST_ATTESTATIONS_URL="${LESSER_HOST_ATTESTATIONS_URL:-$LESSER_HOST_URL}"',
		': "${LESSER_HOST_INSTANCE_KEY_ARN:?LESSER_HOST_INSTANCE_KEY_ARN is required}"',
		'validate_https_custom_domain() {',
		'  NAME="$1"',
		'  VALUE="$2"',
		'  if [ -z "$VALUE" ]; then fail "$NAME is empty"; fi',
		'  case "$VALUE" in https://*) ;; *) fail "$NAME must start with https:// (got: $VALUE)";; esac',
		'  case "$VALUE" in *.lambda-url.*|*amazonaws.com*|*.on.aws*|*cloudfront.net*) fail "$NAME must be a custom domain URL, not an AWS-generated hostname (got: $VALUE)";; esac',
		'}',
		'validate_https_custom_domain "LESSER_HOST_URL" "$LESSER_HOST_URL"',
		'validate_https_custom_domain "LESSER_HOST_ATTESTATIONS_URL" "$LESSER_HOST_ATTESTATIONS_URL"',
		'case "$LESSER_HOST_INSTANCE_KEY_ARN" in arn:*) ;; *) fail "LESSER_HOST_INSTANCE_KEY_ARN must start with arn:";; esac',
		'bool_on() {',
		'  v=$(printf "%s" "$1" | tr "[:upper:]" "[:lower:]")',
		'  case "$v" in true|1|yes|on) return 0 ;; *) return 1 ;; esac',
		'}',
		'enable_agents() {',
		'  echo "Ensuring agents are enabled..."',
		'  STACK_NAME="$APP_SLUG-$STAGE"',
		'  API_FN="$APP_SLUG-$STAGE-api"',
		'  GRAPHQL_FN="$APP_SLUG-$STAGE-graphql"',
		'  GRAPHQL_WS_FN="$APP_SLUG-$STAGE-graphql-ws"',
		'',
		'  update_lambda_env() {',
		'    FN="$1"',
		'    echo "Setting agent env vars on Lambda: $FN"',
		'    CUR=$(aws lambda get-function-configuration --profile managed --function-name "$FN" --output json | jq -c \'.Environment.Variables // {}\')',
		'    NEXT=$(printf "%s" "$CUR" | jq -c \'. + {"ALLOW_AGENTS":"true","ALLOW_AGENT_REGISTRATION":"true"}\')',
		'    ENV=$(jq -nc --argjson vars "$NEXT" \'{Variables:$vars}\')',
		'    aws lambda update-function-configuration --profile managed --function-name "$FN" --environment "$ENV" >/dev/null',
		'  }',
		'',
		'  wait_lambda_update() {',
		'    FN="$1"',
		'    for i in $(seq 1 60); do',
		'      STATUS=$(aws lambda get-function-configuration --profile managed --function-name "$FN" --query "LastUpdateStatus" --output text)',
		'      case "$STATUS" in',
		'        Successful) return 0 ;;',
		'        Failed) fail "Lambda update failed: $FN" ;;',
		'      esac',
		'      sleep 2',
		'    done',
		'    fail "Lambda update timed out: $FN"',
		'  }',
		'',
		'  update_lambda_env "$API_FN"',
		'  update_lambda_env "$GRAPHQL_FN"',
		'  update_lambda_env "$GRAPHQL_WS_FN"',
		'',
		'  wait_lambda_update "$API_FN"',
		'  wait_lambda_update "$GRAPHQL_FN"',
		'  wait_lambda_update "$GRAPHQL_WS_FN"',
		'',
		'  TABLE_NAME=$(aws cloudformation describe-stacks --profile managed --stack-name "$STACK_NAME" --output json | jq -r \'.Stacks[0].Outputs[] | select(.OutputKey=="TableName") | .OutputValue\' | head -n 1)',
		'  test -n "$TABLE_NAME" && test "$TABLE_NAME" != "null"',
		'',
		'  NOW=$(date -u +"%Y-%m-%dT%H:%M:%S.%NZ")',
		'  aws dynamodb update-item --profile managed --region "$TARGET_REGION" --table-name "$TABLE_NAME" \\',
		'    --key \'{"PK":{"S":"INSTANCE#CONFIG"},"SK":{"S":"AGENT_CONFIG"}}\' \\',
		'    --update-expression \'SET allowAgents=:t, allowAgentRegistration=:t, defaultQuarantineDays=:dq, maxAgentsPerOwner=:mao, allowRemoteAgents=:ar, remoteQuarantineDays=:rdq, blockedAgentDomains=:empty, trustedAgentDomains=:empty, agentMaxPostsPerHour=:ampph, verifiedAgentMaxPostsPerHour=:vampph, agentMaxFollowsPerHour=:amfph, verifiedAgentMaxFollowsPerHour=:vamfph, hybridRetrievalEnabled=:hre, hybridRetrievalMaxCandidates=:hrmc, updatedAt=:now\' \\',
		'    --expression-attribute-values \'{":t":{"BOOL":true},":dq":{"N":"7"},":mao":{"N":"3"},":ar":{"BOOL":true},":rdq":{"N":"7"},":empty":{"L":[]},":ampph":{"N":"50"},":vampph":{"N":"200"},":amfph":{"N":"20"},":vamfph":{"N":"100"},":hre":{"BOOL":false},":hrmc":{"N":"200"},":now":{"S":"\'"$NOW"\'"}}\' \\',
		'    --return-values NONE >/dev/null',
		'  echo "Agents enabled."',
		'}',
		'if bool_on "${TIP_ENABLED:-}"; then',
		'  if [ -z "${TIP_CHAIN_ID:-}" ]; then fail "TIP_CHAIN_ID is required when TIP_ENABLED=true"; fi',
		'  case "$TIP_CHAIN_ID" in *[!0-9]*|"") fail "TIP_CHAIN_ID must be a positive integer when TIP_ENABLED=true";; 0) fail "TIP_CHAIN_ID must be > 0 when TIP_ENABLED=true";; esac',
		'  if [ -z "${TIP_CONTRACT_ADDRESS:-}" ]; then fail "TIP_CONTRACT_ADDRESS is required when TIP_ENABLED=true"; fi',
		'fi',
		'jq -n --arg slug "$APP_SLUG" --arg stage "$STAGE" --arg admin_wallet_address "$ADMIN_WALLET_ADDRESS" --arg admin_username "$ADMIN_USERNAME" --arg admin_wallet_chain_id "${ADMIN_WALLET_CHAIN_ID:-}" --arg consent_message "$CONSENT_MESSAGE" --arg consent_signature "${CONSENT_SIGNATURE:-}" --arg lesser_host_url "${LESSER_HOST_URL:-}" --arg lesser_host_attestations_url "${LESSER_HOST_ATTESTATIONS_URL:-}" --arg lesser_host_instance_key_arn "${LESSER_HOST_INSTANCE_KEY_ARN:-}" --arg translation_enabled "${TRANSLATION_ENABLED:-}" --arg tip_enabled "${TIP_ENABLED:-}" --arg tip_chain_id "${TIP_CHAIN_ID:-}" --arg tip_contract_address "${TIP_CONTRACT_ADDRESS:-}" --arg ai_enabled "${AI_ENABLED:-}" --arg ai_moderation_enabled "${AI_MODERATION_ENABLED:-}" --arg ai_nsfw_detection_enabled "${AI_NSFW_DETECTION_ENABLED:-}" --arg ai_spam_detection_enabled "${AI_SPAM_DETECTION_ENABLED:-}" --arg ai_pii_detection_enabled "${AI_PII_DETECTION_ENABLED:-}" --arg ai_content_detection_enabled "${AI_CONTENT_DETECTION_ENABLED:-}" \'def bool($v): ($v|ascii_downcase) as $x | ($x=="true" or $x=="1" or $x=="yes" or $x=="on"); {"schema":1,"slug":$slug,"stage":$stage,"admin_wallet_address":$admin_wallet_address,"admin_username":$admin_username} | if $admin_wallet_chain_id != "" then .admin_wallet_chain_id = ($admin_wallet_chain_id|tonumber) else . end | if $consent_message != "" then .consent_message = $consent_message else . end | if $consent_signature != "" then .consent_signature = $consent_signature else . end | if $lesser_host_url != "" then .lesser_host_url = $lesser_host_url else . end | if $lesser_host_attestations_url != "" then .lesser_host_attestations_url = $lesser_host_attestations_url elif $lesser_host_url != "" then .lesser_host_attestations_url = $lesser_host_url else . end | if $lesser_host_instance_key_arn != "" then .lesser_host_instance_key_arn = $lesser_host_instance_key_arn else . end | if $translation_enabled != "" then .translation_enabled = bool($translation_enabled) else . end | if $tip_enabled != "" then .tip_enabled = bool($tip_enabled) else . end | if $tip_chain_id != "" then .tip_chain_id = ($tip_chain_id|tonumber) else . end | if $tip_contract_address != "" then .tip_contract_address = $tip_contract_address else . end | if $ai_enabled != "" then .ai_enabled = bool($ai_enabled) else . end | if $ai_moderation_enabled != "" then .ai_moderation_enabled = bool($ai_moderation_enabled) else . end | if $ai_nsfw_detection_enabled != "" then .ai_nsfw_detection_enabled = bool($ai_nsfw_detection_enabled) else . end | if $ai_spam_detection_enabled != "" then .ai_spam_detection_enabled = bool($ai_spam_detection_enabled) else . end | if $ai_pii_detection_enabled != "" then .ai_pii_detection_enabled = bool($ai_pii_detection_enabled) else . end | if $ai_content_detection_enabled != "" then .ai_content_detection_enabled = bool($ai_content_detection_enabled) else . end\' > "$PROVISION_INPUT"',
		'STAGE_DOMAIN="$BASE_DOMAIN"',
		'if [ "$STAGE" != "live" ]; then STAGE_DOMAIN="$STAGE.$BASE_DOMAIN"; fi',
		'if [ "$RUN_MODE" = "lesser" ]; then',
		'  ./lesser up --app "$APP_SLUG" --base-domain "$BASE_DOMAIN" --aws-profile managed --provisioning-input "$PROVISION_INPUT" --release-dir "$LESSER_RELEASE_DIR"',
		'  if [ -n "${CONSENT_MESSAGE_B64:-}" ] && [ -n "${CONSENT_SIGNATURE:-}" ]; then ./lesser init-admin --base-domain "$BASE_DOMAIN" --aws-profile managed --provisioning-input "$PROVISION_INPUT"; else echo "Skipping init-admin (missing consent message/signature)."; fi',
		'  enable_agents',
		'  RECEIPT_PATH="$STATE_DIR/state.json"',
		'  test -f "$RECEIPT_PATH"',
		'  LAMBDA_METADATA_PATH="$STATE_DIR/deploy/lambda-assets/metadata.json"',
		'  test -f "$LAMBDA_METADATA_PATH"',
		'  MANAGED_RECEIPT_PATH="$STATE_DIR/state.managed.json"',
		"  jq --slurpfile release \"$LESSER_RELEASE_DIR/lesser-release.json\" --slurpfile bundle \"$LESSER_RELEASE_DIR/lesser-lambda-bundle.json\" --slurpfile metadata \"$LAMBDA_METADATA_PATH\" '. + {managed_deploy_artifacts:{mode:($metadata[0].mode // \"release\"),checksums_path:\"checksums.txt\",release_manifest_path:\"lesser-release.json\",release:{name:($release[0].name // \"\"),version:($release[0].version // \"\"),git_sha:($release[0].git_sha // \"\")},deploy_artifact:{kind:\"lambda_bundle\",path:($bundle[0].bundle.path // \"\"),manifest_path:\"lesser-lambda-bundle.json\",files:($metadata[0].files // ($bundle[0].files | map(.path))),prepared_at:($metadata[0].prepared_at // \"\")}}}' \"$RECEIPT_PATH\" > \"$MANAGED_RECEIPT_PATH\"",
		'  aws s3 cp "$MANAGED_RECEIPT_PATH" "s3://$ARTIFACT_BUCKET/$RECEIPT_S3_KEY"',
		'  if [ -f /tmp/bootstrap.json ]; then aws s3 cp /tmp/bootstrap.json "s3://$ARTIFACT_BUCKET/$BOOTSTRAP_S3_KEY"; fi',
		'elif [ "$RUN_MODE" = "lesser-body" ]; then',
		'  echo "Deploying lesser-body (AgentCore MCP)..."',
		'  BODY_OWNER="${LESSER_BODY_GITHUB_OWNER:-equaltoai}"',
		'  BODY_REPO="${LESSER_BODY_GITHUB_REPO:-lesser-body}"',
		'  BODY_TAG="${LESSER_BODY_VERSION:-}"',
		'  BODY_TAG_NORMALIZED=$(printf "%s" "$BODY_TAG" | tr "[:upper:]" "[:lower:]")',
		'  if [ -z "$BODY_TAG" ] || [ "$BODY_TAG_NORMALIZED" = "latest" ]; then',
		'    echo "Resolving latest lesser-body release..."',
		'    BODY_TAG=$(resolve_latest_release_tag "$BODY_OWNER" "$BODY_REPO")',
		'  fi',
		'  test -n "$BODY_TAG" && test "$BODY_TAG" != "null"',
		'  echo "Using lesser-body release: $BODY_TAG"',
		'  BODY_RELEASE_DIR="$(pwd)/lesser-body-release"',
		'  prepare_lesser_body_release_dir "$BODY_RELEASE_DIR" "$BODY_OWNER" "$BODY_REPO" "$BODY_TAG" "$STAGE"',
		'  BODY_ASSET_BUCKET="cdk-hnb659fds-assets-$TARGET_ACCOUNT_ID-$TARGET_REGION"',
		'  BODY_ASSET_PREFIX="managed/lesser-body/$APP_SLUG/$STAGE/$BODY_TAG"',
		'  AWS_PROFILE=managed bash "$BODY_RELEASE_DIR/deploy-lesser-body-from-release.sh" --stack-name "$APP_SLUG-$STAGE-lesser-body" --asset-bucket "$BODY_ASSET_BUCKET" --asset-prefix "$BODY_ASSET_PREFIX" --app "$APP_SLUG" --stage "$STAGE" --base-domain "$BASE_DOMAIN"',
		'  BODY_PARAM="/$APP_SLUG/$STAGE/lesser-body/exports/v1/mcp_lambda_arn"',
		'  BODY_LAMBDA_ARN=$(aws ssm get-parameter --profile managed --name "$BODY_PARAM" --query "Parameter.Value" --output text)',
		'  test -n "$BODY_LAMBDA_ARN" && test "$BODY_LAMBDA_ARN" != "null"',
		'  BODY_RECEIPT_PATH="$STATE_DIR/body-state.json"',
		'  BODY_RELEASE_GIT_SHA=$(jq -r \'.git_sha // empty\' "$BODY_RELEASE_DIR/lesser-body-release.json")',
		'  jq -n --arg stage "$STAGE" --arg base_domain "$BASE_DOMAIN" --arg mcp_url "https://api.$STAGE_DOMAIN/mcp/{actor}" --arg version "$BODY_TAG" --arg mcp_lambda_arn "$BODY_LAMBDA_ARN" --arg release_git_sha "$BODY_RELEASE_GIT_SHA" --arg template_path "lesser-body-managed-$STAGE.template.json" \'{version:1,stage:$stage,base_domain:$base_domain,mcp_url:$mcp_url,lesser_body_version:$version,mcp_lambda_arn:$mcp_lambda_arn,managed_deploy_artifacts:{mode:"release",checksums_path:"checksums.txt",release_manifest_path:"lesser-body-release.json",release:{name:"lesser-body",version:$version,git_sha:$release_git_sha,source_checkout_required:false,npm_install_required:false},deploy_artifact:{kind:"lesser_body_managed_deploy",path:"lesser-body.zip",manifest_path:"lesser-body-deploy.json",script_path:"deploy-lesser-body-from-release.sh",template_path:$template_path}}}\' > "$BODY_RECEIPT_PATH"',
		'  aws s3 cp "$BODY_RECEIPT_PATH" "s3://$ARTIFACT_BUCKET/$RECEIPT_S3_KEY"',
		'elif [ "$RUN_MODE" = "lesser-mcp" ]; then',
		'  echo "Wiring POST /mcp/{actor} on existing Lesser API domain..."',
		'  echo "Installing Lesser lambda bundle from release assets..."',
		'  LESSER_MCP_ASSET_ROOT="$STATE_DIR/deploy/lambda-assets"',
		'  install_lesser_lambda_bundle "$LESSER_RELEASE_DIR" "$LESSER_MCP_ASSET_ROOT"',
		'  HOSTED_ZONE_NAME="${BASE_DOMAIN%.}."',
		'  HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --profile managed --dns-name "$HOSTED_ZONE_NAME" --output json | jq -r --arg name "$HOSTED_ZONE_NAME" \'.HostedZones[] | select(.Name==$name and (.Config.PrivateZone|not)) | .Id\' | head -n 1)',
		'  test -n "$HOSTED_ZONE_ID" && test "$HOSTED_ZONE_ID" != "null"',
		'  HOSTED_ZONE_ID="${HOSTED_ZONE_ID#/hostedzone/}"',
		'  cd infra/cdk',
		'  AWS_PROFILE=managed cdk deploy "$APP_SLUG-$STAGE" --require-approval never -c app="$APP_SLUG" -c baseDomain="$BASE_DOMAIN" -c hostedZoneId="$HOSTED_ZONE_ID" -c stage="$STAGE" -c bodyEnabled=true -c soulEnabled=true -c lambdaAssetRoot="$LESSER_MCP_ASSET_ROOT" -c lesserHostUrl="$LESSER_HOST_URL" -c lesserHostAttestationsUrl="$LESSER_HOST_ATTESTATIONS_URL" -c lesserHostInstanceKeyArn="$LESSER_HOST_INSTANCE_KEY_ARN" -c translationEnabled="$TRANSLATION_ENABLED" -c tipEnabled="$TIP_ENABLED" -c tipChainId="${TIP_CHAIN_ID:-}" -c tipContractAddress="${TIP_CONTRACT_ADDRESS:-}"',
		'  cd - >/dev/null',
		'  enable_agents',
		'  MCP_BODY_PARAM="/$APP_SLUG/$STAGE/lesser-body/exports/v1/mcp_lambda_arn"',
		'  MCP_LAMBDA_ARN=$(aws ssm get-parameter --profile managed --name "$MCP_BODY_PARAM" --query "Parameter.Value" --output text)',
		'  test -n "$MCP_LAMBDA_ARN" && test "$MCP_LAMBDA_ARN" != "null"',
		'  MCP_RECEIPT_PATH="$STATE_DIR/mcp-state.json"',
		'  MCP_METADATA_PATH="$LESSER_MCP_ASSET_ROOT/metadata.json"',
		'  test -f "$MCP_METADATA_PATH"',
		"  jq -n --arg stage \"$STAGE\" --arg base_domain \"$BASE_DOMAIN\" --arg mcp_url \"https://api.$STAGE_DOMAIN/mcp/{actor}\" --arg mcp_lambda_arn \"$MCP_LAMBDA_ARN\" --arg lesser_body_version \"${LESSER_BODY_VERSION:-}\" --slurpfile release \"$LESSER_RELEASE_DIR/lesser-release.json\" --slurpfile bundle \"$LESSER_RELEASE_DIR/lesser-lambda-bundle.json\" --slurpfile metadata \"$MCP_METADATA_PATH\" '({version:1,stage:$stage,base_domain:$base_domain,mcp_url:$mcp_url,mcp_lambda_arn:$mcp_lambda_arn} + (if $lesser_body_version != \"\" then {lesser_body_version:$lesser_body_version} else {} end) + {managed_deploy_artifacts:{mode:($metadata[0].mode // \"release\"),checksums_path:\"checksums.txt\",release_manifest_path:\"lesser-release.json\",release:{name:($release[0].name // \"\"),version:($release[0].version // \"\"),git_sha:($release[0].git_sha // \"\")},deploy_artifact:{kind:\"lambda_bundle\",path:($bundle[0].bundle.path // \"\"),manifest_path:\"lesser-lambda-bundle.json\",files:($metadata[0].files // ($bundle[0].files | map(.path))),prepared_at:($metadata[0].prepared_at // \"\")}}})' > \"$MCP_RECEIPT_PATH\"",
		'  aws s3 cp "$MCP_RECEIPT_PATH" "s3://$ARTIFACT_BUCKET/$RECEIPT_S3_KEY"',
		'else',
		'  fail "unknown RUN_MODE: $RUN_MODE"',
		'fi',
	].join('\n');
}
