import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';

import {
	findLambdaEntryByFunctionName,
	findResourceEntries,
	lambdaEnvironment,
	synthTemplate,
	synthTemplateWithContext,
} from './_lesser-host-test-helpers';
import { normalizedBootstrapWalletOverride } from '../lib/setup-bootstrap-wallet';

function setupBootstrapWalletResource(template: ReturnType<typeof synthTemplate>) {
	return findResourceEntries(template, 'AWS::CloudFormation::CustomResource').find(([logicalId]) =>
		logicalId.startsWith('SetupBootstrapWallet')
	);
}

test('default setup bootstrap wallet is generated by a CloudFormation-owned custom resource', () => {
	const template = synthTemplate();
	const resource = setupBootstrapWalletResource(template);
	assert.ok(resource, 'expected setup bootstrap wallet custom resource');
	assert.equal(
		resource[1].Properties?.BootstrapWalletSSMParamName,
		'/lesser-host/lab/setup/bootstrap-wallet-private-key',
	);
	assert.equal(resource[1].Properties?.Stage, 'lab');

	const controlPlane = findLambdaEntryByFunctionName(template, 'control-plane-api');
	assert.ok(controlPlane, 'expected control-plane Lambda');
	const env = lambdaEnvironment(controlPlane[1].Properties);
	assert.deepEqual(
		env.BOOTSTRAP_WALLET_ADDRESS,
		{ 'Fn::GetAtt': [resource[0], 'BootstrapWalletAddress'] },
		'control plane must receive only the custom-resource returned address token',
	);
	assert.doesNotMatch(
		JSON.stringify(env.BOOTSTRAP_WALLET_ADDRESS),
		/^"0x[0-9a-fA-F]{40}"$/,
		'default deploy must not embed a hard-coded bootstrap address',
	);
});

test('explicit bootstrap wallet override is validated and bypasses generated key storage', () => {
	const template = synthTemplateWithContext({
		bootstrapWalletAddress: '0x1234567890ABCDEF1234567890aBcdef12345678',
	});
	const resource = setupBootstrapWalletResource(template);
	assert.equal(resource, undefined, 'override deploy must not create the generated-wallet resource');

	const controlPlane = findLambdaEntryByFunctionName(template, 'control-plane-api');
	assert.ok(controlPlane, 'expected control-plane Lambda');
	const env = lambdaEnvironment(controlPlane[1].Properties);
	assert.equal(
		env.BOOTSTRAP_WALLET_ADDRESS,
		'0x1234567890abcdef1234567890abcdef12345678',
	);
});

test('bootstrap wallet override rejects placeholders and malformed values', () => {
	for (const value of ['<YOUR_BOOTSTRAP_WALLET_ADDRESS>', 'YOUR_BOOTSTRAP_WALLET_ADDRESS', '0x1234']) {
		assert.throws(
			() => normalizedBootstrapWalletOverride(value),
			/bootstrapWalletAddress override must be .*EVM 0x address/,
		);
	}
});

test('AppTheory wrapper no longer reads or writes the generated bootstrap key outside CloudFormation', () => {
	const wrapper = readFileSync(join(process.cwd(), '..', 'scripts', 'app-theory-cdk.sh'), 'utf8');
	const cdkJson = readFileSync(join(process.cwd(), 'cdk.json'), 'utf8');
	assert.doesNotMatch(wrapper, /aws\s+ssm\s+(get|put)-parameter/);
	assert.doesNotMatch(wrapper, /bootstrap-wallet-private-key/);
	assert.match(wrapper, /bootstrapWalletAddress/);
	assert.doesNotMatch(cdkJson, /bootstrapWalletAddress/);
});
