#!/usr/bin/env bash
set -euo pipefail

# P52 corrective #873: post-deploy verifier for the CDK-owned hosted-genesis
# AppTheory MicroVM controller authorizer bearer token.
#
# The authorizer bearer token is NO LONGER manually provisioned. Host CDK owns
# it: a Lambda-backed custom resource generates the token during
# `theory app up` / `cdk deploy`, writes the RAW token to a deterministic SSM
# SecureString, and returns ONLY the sha256 digest + param name to
# CloudFormation. There is no `--token-sha256` input, no
# `hostedGenesisMicrovmAuthorizerTokenSha256` context, and no
# `hostedGenesisMicrovmAuthTokenSSMParamName` context. The prior manual
# `aws ssm put-parameter` operator step is retired.
#
# This script is now a POST-DEPLOY verifier: after `theory app up --stage
# <lab|live>`, it confirms the stack-owned SSM SecureString parameter EXISTS as
# a SecureString — WITHOUT decrypting it, and WITHOUT asking the operator for a
# hash or context value. It never reads, prints, or logs the raw token. Use it
# to confirm the CDK custom resource successfully provisioned the param.
#
# Usage:
#   scripts/hosted-genesis-microvm-preflight.sh \
#       --stage lab \
#       [--region us-east-1]
#
# Exit codes:
#   0  verified (stack-owned SSM param exists as a SecureString)
#   1  verification failed (param missing or not a SecureString)
#   2  prerequisite missing (aws CLI not installed)

usage() {
    cat >&2 <<'USAGE'
Usage: scripts/hosted-genesis-microvm-preflight.sh \
  --stage <lab|live> \
  [--region us-east-1]

Post-deploy verifier: confirms the CDK-owned auth-token SSM SecureString
parameter exists as a SecureString WITHOUT decrypting it. The token is
generated by the Host CDK custom resource during deploy; the operator supplies
only the stage. Never reads or prints the raw token value.
USAGE
}

STAGE=""
REGION=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --stage)
            STAGE="${2:-}"
            shift 2
            ;;
        --region)
            REGION="${2:-}"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "ERROR: unknown argument: $1" >&2
            usage
            exit 1
            ;;
    esac
done

if [[ -z "$STAGE" ]]; then
    echo "ERROR: --stage is required (lab or live)" >&2
    usage
    exit 1
fi

case "$STAGE" in
    lab|live) ;;
    *)
        echo "ERROR: --stage must be 'lab' or 'live' (got '$STAGE')" >&2
        exit 1
        ;;
esac

if ! command -v aws &>/dev/null; then
    echo "ERROR: aws CLI is required to verify the SSM parameter exists" >&2
    exit 2
fi

# The param name is deterministic and CDK-owned. The raw token VALUE is a
# credential generated by the custom resource; this script never reads it.
SSM_PARAM_NAME="/lesser-host/${STAGE}/hosted-genesis/microvm/auth-token"

declare -a aws_args=(--query "Parameters[0]" --output json)
if [[ -n "$REGION" ]]; then
    aws_args+=(--region "$REGION")
fi

# describe-parameters returns metadata only (Type, Name, ARN) — it never returns
# the value, so the raw token is not touched. Require Type=SecureString so a
# plaintext parameter is rejected (a plaintext auth token would be a credential
# leak). The CDK custom resource writes the param as Type=SecureString.
describe_json="$(aws ssm describe-parameters \
    --parameter-filters "Key=Name,Values=$SSM_PARAM_NAME" \
    "${aws_args[@]}" 2>/dev/null || true)"

if [[ -z "$describe_json" || "$describe_json" == "null" ]]; then
    echo "ERROR: stack-owned SSM parameter '$SSM_PARAM_NAME' not found." >&2
    echo "       The Host CDK custom resource should have provisioned it during" >&2
    echo "       'theory app up --stage ${STAGE}'. Re-run the deploy; do NOT manually" >&2
    echo "       put-parameter the raw token (token generation is CDK-owned)." >&2
    exit 1
fi

param_type="$(printf '%s' "$describe_json" | grep -o '"Type"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed -E 's/.*: *"([^"]*)"/\1/' || true)"
if [[ "$param_type" != "SecureString" ]]; then
    echo "ERROR: stack-owned SSM parameter '$SSM_PARAM_NAME' is Type='$param_type', not SecureString." >&2
    echo "       The CDK custom resource must write it as Type=SecureString." >&2
    exit 1
fi

echo "PASS: hosted-genesis MicroVM CDK-owned auth-token verified"
echo "  stage:      ${STAGE}"
echo "  SSM param:  ${SSM_PARAM_NAME} (exists, SecureString, not decrypted)"
echo "  reminder:   token generation is CDK-owned; never put-parameter the raw token"
exit 0
